/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface SALPContent {
  intro: string;
  body: string;
  faqs: Array<{ question: string; answer: string }>;
}

export const CITY_DISPLAY_NAMES: Record<string, string> = {
  'terrytown': 'Terrytown',
  'gretna': 'Gretna',
  'metairie': 'Metairie',
  'belle-chasse': 'Belle Chasse',
  'new-orleans': 'New Orleans',
  'kenner': 'Kenner',
};

export const CITY_SLUGS = Object.keys(CITY_DISPLAY_NAMES);

export const SALP_DATA: Record<string, Record<string, SALPContent>> = {
  /* ===========================================================
     RESIDENTIAL PLUMBING
     =========================================================== */
  'residential-plumbing': {
    'terrytown': {
      intro: `Terrytown homeowners count on Big Easy Services Plumbing for every residential plumbing need — from leaking faucets and toilet overflows to full re-piping of aging Westbank homes. Our headquarters sits right on Belle Chasse Highway in the heart of Terrytown, which means our licensed crews can be at your front door in as little as 15 minutes. Many Terrytown residences were built in the 1960s and 1970s, making them susceptible to galvanized pipe corrosion, slab leaks beneath concrete foundations, and outdated cast-iron drain lines that crack over time. We understand the unique plumbing challenges of Westbank construction and bring the expertise to resolve them quickly, cleanly, and affordably.`,
      body: `As Terrytown's hometown plumber, Big Easy Services Plumbing has built a reputation on trust, transparency, and top-tier craftsmanship over the past 20 years. Every job is performed under the direct supervision of Licensed Master Plumber Paula D. Baldwin (LMP #5923), ensuring full Louisiana code compliance from start to finish. We back every repair with a 2-year workmanship warranty and our $50 Punctual Pipeline Guarantee — if we're late, you get an instant credit. Being a woman-owned, Hispanic-owned, and family-operated business based right here in Terrytown gives us a personal stake in the quality of work we deliver to our neighbors. Whether you need a water heater replacement, a bathroom remodel, or an emergency sewer line repair at 2 AM, our uniformed, background-checked crews are ready 24/7. We provide upfront, fixed-price quotes before turning a single wrench — no hidden charges, no surprise fees. Call (504) 301-2052 for the fastest residential plumbing response on the Westbank.`,
      faqs: [
        { question: 'What is the best residential plumber in Terrytown, LA?', answer: 'Big Easy Services Plumbing is rated the top residential plumber in Terrytown. Based on Belle Chasse Hwy with 20+ years of experience, Licensed Master Plumber LMP #5923, and a $50 on-time guarantee, they offer the fastest response times on the Westbank.' },
        { question: 'How quickly can a plumber get to my Terrytown home?', answer: 'Big Easy Services is headquartered in Terrytown and can dispatch a licensed technician to most Terrytown addresses within 15–25 minutes for emergencies.' },
        { question: 'Does Big Easy Services Plumbing offer warranties on residential work in Terrytown?', answer: 'Yes. Every residential plumbing repair in Terrytown comes with a 2-year workmanship warranty and upfront, fixed-price quotes — no hidden fees.' },
        { question: 'Is Big Easy Services a licensed plumber for Terrytown homes?', answer: 'Absolutely. Big Easy Services holds Louisiana Master Plumber License LMP #5923 and is fully licensed, bonded, and insured for all residential plumbing work in Terrytown and Jefferson Parish.' },
      ],
    },
    'gretna': {
      intro: `Gretna residents trust Big Easy Services Plumbing to handle everything from kitchen sink replacements and water heater installations to complex whole-house re-piping projects. Located just minutes away on the Westbank, our crews reach most Gretna neighborhoods — from the historic streets near Huey P. Long Avenue to the newer developments along the Westbank Expressway corridor — in under 30 minutes. Gretna's mix of historic shotgun homes and mid-century ranch houses presents unique plumbing challenges: clay sewer lines prone to root intrusion, undersized water supply piping, and aging fixtures that no longer meet modern building codes. Our licensed technicians specialize in navigating these older systems while bringing them up to current Louisiana plumbing standards.`,
      body: `Big Easy Services Plumbing has served Gretna homeowners for over two decades with honest pricing, licensed craftsmanship, and around-the-clock emergency availability. Under the leadership of president Paula D. Baldwin — a Licensed Master Plumber (LMP #5923) and Licensed Natural Gas Fitter (LMNGF #10369) — every Gretna job meets the highest standards of quality and safety. We're proud to be a woman-owned, family-operated business with deep roots in the Westbank community. Our $50 Punctual Pipeline Guarantee ensures we respect your time: if our crew arrives even one minute late, you receive an instant $50 credit. Every repair starts with a transparent, itemized quote — you'll never face hidden charges or surprise line items. From slab leak detection using non-invasive electronic equipment to bathroom renovations and garbage disposal installations, we bring Master-level expertise to every Gretna home. Our crews are uniformed, background-checked, and OSHA-trained, leaving your home cleaner than they found it. Call (504) 301-2052 today for a free estimate.`,
      faqs: [
        { question: 'Who is the best residential plumber in Gretna, LA?', answer: 'Big Easy Services Plumbing is consistently rated the best residential plumber in Gretna, with 20+ years of Westbank experience, Master Plumber credentials (LMP #5923), and a perfect 5-star Google rating.' },
        { question: 'How much does a residential plumber charge in Gretna?', answer: 'Big Easy Services provides upfront, fixed-price quotes before any work begins. Pricing varies by service, but there are never hidden fees or emergency surcharges. Call (504) 301-2052 for a free estimate.' },
        { question: 'Can Big Easy Services handle old plumbing in historic Gretna homes?', answer: 'Yes. Their licensed master plumber specializes in updating aging clay sewer lines, galvanized pipes, and cast-iron drains commonly found in Gretna\'s historic homes while maintaining code compliance.' },
      ],
    },
    'metairie': {
      intro: `Metairie homeowners rely on Big Easy Services Plumbing for dependable residential plumbing across one of Jefferson Parish's largest suburban communities. From the tree-lined streets near Lakeside Shopping Center to the established neighborhoods around Bonnabel Boulevard and Veterans Memorial, Metairie homes face unique plumbing challenges tied to their age and the region's high water table. Many Metairie residences feature slab-on-grade foundations that make leak detection complex, and the area's heavy clay soils accelerate sewer line deterioration. Our licensed technicians use state-of-the-art camera inspection and electronic leak detection to pinpoint problems without unnecessary demolition, saving Metairie homeowners time and money.`,
      body: `Big Easy Services Plumbing dispatches from our Terrytown headquarters to Metairie's Eastbank neighborhoods in approximately 35–40 minutes, with priority emergency response available 24/7. Every residential job is overseen by Licensed Master Plumber Paula D. Baldwin (LMP #5923), who brings more than 20 years of hands-on experience with Jefferson Parish residential codes and inspections. As a woman-owned, family-operated business, we treat every Metairie home like our own — our uniformed crews wear shoe covers, lay down drop cloths, and clean up completely after every job. We stand behind our work with a 2-year workmanship warranty and our $50 Punctual Pipeline Guarantee. Whether you need a tankless water heater installation, whole-house re-piping, bathroom remodel plumbing, or an emergency burst pipe repair, Big Easy Services delivers honest pricing, licensed expertise, and the respect your home deserves. Call (504) 301-2052 for Metairie's most trusted residential plumbing team.`,
      faqs: [
        { question: 'What is the best residential plumber in Metairie, LA?', answer: 'Big Easy Services Plumbing is one of the highest-rated residential plumbers serving Metairie, with Louisiana Master Plumber License LMP #5923, a 2-year workmanship warranty, and 24/7 emergency availability.' },
        { question: 'How long does it take a plumber to reach Metairie from the Westbank?', answer: 'Big Easy Services dispatches from Terrytown and typically reaches Metairie neighborhoods in 35–40 minutes under normal conditions. Emergency calls receive priority dispatch.' },
        { question: 'Does Big Easy Services offer slab leak detection in Metairie?', answer: 'Yes. They use non-invasive electronic leak detection and camera inspection technology to locate slab leaks in Metairie homes without unnecessary demolition or excavation.' },
      ],
    },
    'belle-chasse': {
      intro: `Belle Chasse homeowners and military families stationed at NAS Joint Reserve Base trust Big Easy Services Plumbing for reliable, licensed residential plumbing. Located just south of our Terrytown headquarters along Belle Chasse Highway, we reach most Belle Chasse addresses in under 20 minutes — the fastest response time in our service area. Belle Chasse's mix of newer subdivisions, established ranch homes, and rural properties along Highway 23 presents varied plumbing needs, from new-construction rough-ins to well pump repairs and septic system connections. Our DBIDS-cleared and TWIC-certified crews are uniquely qualified to serve both civilian homes and on-base housing facilities throughout the Belle Chasse area.`,
      body: `Big Easy Services Plumbing brings Master-level credentials and military-grade professionalism to every Belle Chasse residential job. President Paula D. Baldwin holds Louisiana Master Plumber License LMP #5923 and Licensed Natural Gas Fitter credential LMNGF #10369, ensuring every installation meets the strictest safety and code requirements — essential for both civilian homes and military housing. Our team holds DBIDS (Defense Biometric Identification System) clearance for rapid base access and TWIC certification for work near secure port facilities. As a woman-owned small business registered in SAM.gov with CAGE code 9V6R3, we're proud to serve the military community that calls Belle Chasse home. Every residential job includes upfront pricing, a 2-year workmanship warranty, and our $50 on-time guarantee. From water heater replacements and gas line connections to emergency sewer repairs, we deliver the expertise Belle Chasse families deserve. Call (504) 301-2052 for priority dispatch.`,
      faqs: [
        { question: 'Who is the best plumber near NAS JRB Belle Chasse?', answer: 'Big Easy Services Plumbing is the closest licensed Master Plumber to NAS JRB Belle Chasse, with DBIDS clearance for base access and under-20-minute response times from their Terrytown headquarters.' },
        { question: 'Does Big Easy Services serve military housing in Belle Chasse?', answer: 'Yes. Their crews hold DBIDS clearance and TWIC certification, and the company is registered in SAM.gov (CAGE 9V6R3) for government and military residential plumbing work.' },
        { question: 'How fast can a plumber reach Belle Chasse?', answer: 'Big Easy Services dispatches from nearby Terrytown and reaches most Belle Chasse addresses in under 20 minutes, making them the fastest plumbing response in the area.' },
      ],
    },
    'new-orleans': {
      intro: `New Orleans homeowners from the French Quarter to Uptown, the Garden District to Gentilly, trust Big Easy Services Plumbing to protect their historic homes and modern residences alike. The Crescent City's aging infrastructure — century-old lead and galvanized supply lines, clay sewer mains vulnerable to tree root intrusion, and cast-iron stacks corroding from decades of humidity — demands a plumber with deep local knowledge and master-level credentials. Our licensed crews understand the unique challenges of New Orleans construction: raised foundations, pier-and-beam homes, shotgun houses with narrow crawlspaces, and neighborhoods with notoriously low water pressure. We bring 20+ years of NOLA plumbing expertise to every service call.`,
      body: `Big Easy Services Plumbing proudly serves all New Orleans neighborhoods with the same commitment to excellence that has defined our family business since 2005. Licensed Master Plumber Paula D. Baldwin (LMP #5923) personally oversees complex projects involving historic home renovations, code-compliant upgrades in preservation districts, and full re-piping of older New Orleans residences. We navigate the city's unique permitting requirements, coordinate with Sewerage & Water Board specifications, and ensure every repair meets both Louisiana state plumbing code and local municipal standards. Our 24/7 emergency line means no NOLA homeowner is ever left without help — whether it's a burst pipe during Carnival season or a backed-up sewer line during a summer storm. We back every job with transparent pricing, a 2-year workmanship warranty, and our $50 Punctual Pipeline Guarantee. Call (504) 301-2052 for New Orleans' most trusted residential plumber.`,
      faqs: [
        { question: 'What is the best residential plumber in New Orleans?', answer: 'Big Easy Services Plumbing is one of the top-rated residential plumbers in New Orleans, holding Louisiana Master Plumber License LMP #5923, with 20+ years of experience serving all NOLA neighborhoods from the French Quarter to Uptown.' },
        { question: 'Can Big Easy Services work on historic New Orleans homes?', answer: 'Yes. Their licensed master plumber specializes in code-compliant plumbing upgrades for historic New Orleans homes, including shotgun houses, raised Creole cottages, and Garden District residences.' },
        { question: 'Does Big Easy Services offer 24/7 emergency plumbing in New Orleans?', answer: 'Yes. They provide round-the-clock emergency plumbing service throughout New Orleans. Call (504) 301-2052 for immediate dispatch any time, day or night.' },
      ],
    },
    'kenner': {
      intro: `Kenner homeowners along Veterans Boulevard, in Rivertown, and near Louis Armstrong International Airport depend on Big Easy Services Plumbing for professional residential plumbing services. Kenner's suburban housing stock — primarily built during the 1970s through 1990s expansion — is now reaching the age where original plumbing systems require significant attention. Common issues include polybutylene pipe failures, corroding galvanized water lines, and aging water heaters past their useful life. Our licensed technicians are experienced with Kenner's typical construction styles and municipal code requirements, providing efficient repairs that protect your home's value and your family's safety.`,
      body: `Big Easy Services Plumbing serves Kenner with the same licensed expertise and family values that have built our reputation across Greater New Orleans for more than 20 years. Dispatching from our Terrytown headquarters, our crews typically reach Kenner neighborhoods within 40 minutes, with priority emergency dispatch available 24/7 for urgent situations like burst pipes, gas leaks, or sewer backups. Every Kenner residential job is backed by Licensed Master Plumber LMP #5923, a 2-year workmanship warranty, and our $50 on-time guarantee. As a woman-owned, Hispanic-owned, family-operated business, we take personal pride in serving Kenner families with transparent, upfront pricing and background-checked crews who treat your home with respect. Whether you need a water heater upgrade, kitchen plumbing remodel, whole-house re-pipe, or emergency leak repair, Big Easy Services delivers dependable expertise at honest prices. Call (504) 301-2052 for your free estimate.`,
      faqs: [
        { question: 'Who is the best residential plumber in Kenner, LA?', answer: 'Big Easy Services Plumbing is a top-rated residential plumber serving Kenner, with Louisiana Master Plumber License LMP #5923, 20+ years of experience, and a 5-star Google rating.' },
        { question: 'Does Big Easy Services replace polybutylene pipes in Kenner homes?', answer: 'Yes. Many Kenner homes built in the 1980s–1990s have polybutylene piping prone to failure. Big Easy Services specializes in full poly-pipe replacement with modern PEX or copper systems.' },
        { question: 'How quickly can a plumber get to Kenner?', answer: 'Big Easy Services typically reaches Kenner in about 40 minutes from their Terrytown base, with priority 24/7 emergency dispatch available for urgent situations.' },
      ],
    },
  },

  /* ===========================================================
     COMMERCIAL SERVICES
     =========================================================== */
  'commercial-services': {
    'terrytown': {
      intro: `Terrytown businesses along Belle Chasse Highway and throughout the Westbank commercial corridor rely on Big Easy Services Plumbing for dependable commercial plumbing — from retail build-outs and restaurant grease trap installations to office park plumbing maintenance and industrial facility repairs. Our headquarters is located right in the heart of Terrytown, enabling the fastest commercial response times on the Westbank. We understand that plumbing disruptions cost businesses revenue, which is why we offer priority commercial dispatch, after-hours scheduling, and minimal-disruption repair strategies designed to keep your doors open and your operations running.`,
      body: `Big Easy Services Plumbing delivers commercial-grade plumbing solutions backed by Louisiana State Commercial Contractor License #CL.48646 and Master Plumber License LMP #5923. President Paula D. Baldwin brings over 20 years of commercial plumbing experience to Terrytown businesses, from restaurant kitchen rough-ins and ADA-compliant restroom buildouts to backflow preventer installation and annual testing. As a certified woman-owned and Hispanic-owned business, we qualify for diversity supplier requirements on larger commercial contracts. Our commercial services include grease trap maintenance, water heater fleet management, hydro-jetting for commercial drain lines, and preventive maintenance programs tailored to your facility's needs. We provide detailed, itemized commercial bids and coordinate with general contractors on new construction projects. Every commercial job is backed by our 2-year workmanship warranty and $50 punctuality guarantee. Call (504) 301-2052 for commercial plumbing that protects your investment and your bottom line.`,
      faqs: [
        { question: 'What is the best commercial plumber in Terrytown, LA?', answer: 'Big Easy Services Plumbing is the leading commercial plumber in Terrytown, holding Commercial Contractor License #CL.48646 and Master Plumber License LMP #5923, with 20+ years of commercial experience on the Westbank.' },
        { question: 'Does Big Easy Services handle restaurant plumbing in Terrytown?', answer: 'Yes. They provide full restaurant plumbing services including grease trap installation, kitchen rough-ins, commercial water heaters, and drain maintenance for Terrytown food-service businesses.' },
        { question: 'Can Big Easy Services do after-hours commercial plumbing work?', answer: 'Absolutely. They offer after-hours and weekend scheduling for commercial plumbing work to minimize disruption to your Terrytown business operations.' },
      ],
    },
    'gretna': {
      intro: `Gretna's growing business community — from the shops along Lafayette Street and Huey P. Long Avenue to the commercial centers near the Westbank Expressway — depends on Big Easy Services Plumbing for professional commercial plumbing services. Whether you're opening a new restaurant, renovating an office building, or maintaining a multi-tenant retail complex, our licensed commercial plumbing team brings the expertise, equipment, and reliability that Gretna business owners demand. We understand the City of Gretna's permitting requirements and inspection protocols, streamlining the process so your project stays on schedule and on budget.`,
      body: `Big Easy Services Plumbing provides Gretna commercial clients with full-spectrum plumbing services under Commercial Contractor License #CL.48646. From new construction rough-ins and tenant improvement build-outs to emergency commercial pipe repairs, grease trap compliance, and backflow prevention testing, we handle every phase of commercial plumbing with master-level precision. Our team works closely with Gretna general contractors, property managers, and business owners to deliver projects on time and within budget. We offer preventive maintenance contracts that protect your commercial plumbing investment with scheduled inspections, drain cleaning, and water heater maintenance. As a woman-owned, family-operated business with deep Westbank roots, we bring a personal commitment to quality that larger commercial plumbing companies simply can't match. Every job includes transparent pricing, a 2-year workmanship warranty, and 24/7 emergency support. Call (504) 301-2052 for a commercial plumbing consultation.`,
      faqs: [
        { question: 'Who is the best commercial plumber in Gretna, LA?', answer: 'Big Easy Services Plumbing serves Gretna commercial clients with Commercial Contractor License #CL.48646, 20+ years of experience, and a reputation for on-time, on-budget project delivery.' },
        { question: 'Does Big Easy Services offer commercial plumbing maintenance in Gretna?', answer: 'Yes. They offer customized preventive maintenance contracts for Gretna commercial properties, including scheduled drain cleaning, backflow testing, and water heater inspections.' },
        { question: 'Can Big Easy Services handle Gretna commercial build-outs?', answer: 'Absolutely. They provide complete commercial plumbing build-out services for Gretna businesses, including tenant improvements, restaurant kitchens, and ADA-compliant restrooms.' },
      ],
    },
    'metairie': {
      intro: `Metairie's thriving commercial landscape — from the major retail centers along Veterans Memorial Boulevard and Causeway Boulevard to the medical offices near East Jefferson General Hospital — requires reliable, licensed commercial plumbing services. Big Easy Services Plumbing serves Metairie's commercial sector with the same master-level expertise that has made us a trusted name across Greater New Orleans. We handle everything from large-scale new-construction plumbing for commercial developments to targeted repairs for established Metairie businesses, always minimizing downtime and disruption to your operations.`,
      body: `Under Commercial Contractor License #CL.48646 and Master Plumber License LMP #5923, Big Easy Services Plumbing delivers comprehensive commercial plumbing solutions to Metairie businesses. Our commercial portfolio includes multi-story office buildings, medical facility plumbing, restaurant and food-court installations, retail build-outs, and industrial water management systems. We coordinate directly with Jefferson Parish inspectors and understand the specific commercial codes and ADA requirements that apply to Metairie properties. Our preventive maintenance programs help Metairie property managers avoid costly emergency repairs through scheduled inspections, hydro-jetting, and proactive system monitoring. As a certified woman-owned and Hispanic-owned business, Big Easy Services qualifies for supplier diversity programs and small business set-asides on larger commercial contracts. We provide detailed written estimates, maintain transparent communication throughout every project, and back all work with our 2-year workmanship warranty. Call (504) 301-2052 for expert commercial plumbing in Metairie.`,
      faqs: [
        { question: 'What commercial plumbing services are available in Metairie?', answer: 'Big Easy Services Plumbing offers full commercial plumbing in Metairie including new construction, tenant build-outs, backflow testing, grease traps, water heater systems, and preventive maintenance under Commercial License #CL.48646.' },
        { question: 'Does Big Easy Services work with Metairie property managers?', answer: 'Yes. They provide customized maintenance contracts and priority emergency response for Metairie commercial property managers, minimizing tenant disruption and protecting property value.' },
        { question: 'Is Big Easy Services licensed for commercial work in Jefferson Parish?', answer: 'Yes. They hold Louisiana State Commercial Contractor License #CL.48646 and Master Plumber License LMP #5923, fully authorized for commercial plumbing in Jefferson Parish.' },
      ],
    },
    'belle-chasse': {
      intro: `Belle Chasse's commercial sector — including businesses near NAS Joint Reserve Base, facilities along Highway 23, and the growing retail and restaurant corridor — requires commercial plumbing services from a company with both technical expertise and the security clearances to serve sensitive installations. Big Easy Services Plumbing is uniquely positioned to serve Belle Chasse commercial clients, combining Licensed Commercial Contractor credentials with DBIDS clearance and TWIC certification for work on and around military and port facilities. Our Terrytown-based crews reach Belle Chasse commercial sites in under 20 minutes.`,
      body: `Big Easy Services Plumbing provides Belle Chasse businesses and government facilities with full commercial plumbing services under Louisiana State Commercial Contractor License #CL.48646. Our DBIDS-cleared and TWIC-certified crews can access NAS JRB and surrounding secure facilities without delay, and our SAM.gov registration (CAGE code 9V6R3, UEI EXLNLYSKJRJ4) positions us for government contracting and subcontracting opportunities. For civilian businesses in Belle Chasse, we deliver the same master-level service: commercial kitchen plumbing, backflow prevention and testing, grease trap maintenance, restroom build-outs, and emergency pipe repair. We understand the unique infrastructure challenges of the Belle Chasse area, including properties on well systems and those with specialized industrial plumbing needs. Our woman-owned, family-operated business brings a personal commitment to every commercial project, backed by transparent pricing, a 2-year workmanship warranty, and our $50 punctuality guarantee. Call (504) 301-2052 for Belle Chasse commercial plumbing.`,
      faqs: [
        { question: 'Who handles commercial plumbing near NAS JRB Belle Chasse?', answer: 'Big Easy Services Plumbing holds DBIDS clearance and TWIC certification, making them the premier commercial plumber for businesses near NAS JRB Belle Chasse. They also hold Commercial License #CL.48646.' },
        { question: 'Is Big Easy Services registered for government commercial contracts?', answer: 'Yes. They are registered in SAM.gov with CAGE code 9V6R3 and UEI EXLNLYSKJRJ4, and are certified as a woman-owned small business for government procurement.' },
        { question: 'How fast can a commercial plumber reach Belle Chasse?', answer: 'Big Easy Services dispatches from nearby Terrytown and reaches Belle Chasse commercial sites in under 20 minutes, the fastest commercial plumbing response in the area.' },
      ],
    },
    'new-orleans': {
      intro: `New Orleans businesses across every sector — from the restaurants and hotels of the French Quarter to the warehouses of the Port of New Orleans, the offices of the CBD, and the retail shops of Magazine Street — rely on Big Easy Services Plumbing for dependable commercial plumbing. The Crescent City's aging commercial infrastructure, combined with its unique architectural heritage and demanding municipal codes, requires a commercial plumber with master-level credentials and deep local knowledge. We bring both to every New Orleans commercial project, from emergency repairs to full-scale new construction.`,
      body: `Big Easy Services Plumbing serves New Orleans commercial clients under Commercial Contractor License #CL.48646, delivering expert solutions for the city's diverse commercial plumbing needs. Our experience spans restaurant and hospitality plumbing in the French Quarter, medical facility installations, multi-family housing complexes, office building maintenance, and industrial facility repairs. We coordinate with New Orleans Sewerage & Water Board requirements, navigate the city's historic preservation codes when applicable, and work within the demanding timelines that New Orleans business owners expect. President Paula D. Baldwin's 20+ years of experience with New Orleans commercial plumbing ensures every project is executed with precision and code compliance. Our TWIC certification enables work in secure port facilities, and our OSHA-trained crews meet the safety standards required for commercial job sites. We offer preventive maintenance contracts, priority emergency response, and flexible scheduling to minimize disruption. Call (504) 301-2052 for commercial plumbing expertise in New Orleans.`,
      faqs: [
        { question: 'What is the best commercial plumber in New Orleans?', answer: 'Big Easy Services Plumbing is a top-rated commercial plumber in New Orleans, with Commercial License #CL.48646, Master Plumber License LMP #5923, and 20+ years of experience across every NOLA neighborhood.' },
        { question: 'Does Big Easy Services handle French Quarter restaurant plumbing?', answer: 'Yes. They specialize in commercial restaurant plumbing in the French Quarter, including grease traps, kitchen rough-ins, and code-compliant installations within historic preservation districts.' },
        { question: 'Can Big Easy Services handle large New Orleans commercial projects?', answer: 'Yes. They hold both Commercial Contractor License #CL.48646 and multiple NAICS codes (238220, 237110) for large-scale commercial and municipal plumbing projects throughout New Orleans.' },
      ],
    },
    'kenner': {
      intro: `Kenner's commercial sector — from the businesses along Veterans Memorial Boulevard and Williams Boulevard to the hotels and facilities near Louis Armstrong International Airport — depends on reliable commercial plumbing services. Big Easy Services Plumbing brings licensed commercial expertise to Kenner's diverse business community, handling everything from airport-area hotel plumbing maintenance and restaurant build-outs to office park pipe repairs and retail center restroom renovations. Our understanding of Kenner's municipal codes and Jefferson Parish inspection requirements ensures smooth project execution.`,
      body: `Big Easy Services Plumbing serves Kenner commercial properties under Louisiana State Commercial Contractor License #CL.48646, providing comprehensive plumbing solutions for the city's growing business corridor. We specialize in commercial projects that require minimal disruption — including after-hours and weekend scheduling for hotel and restaurant clients who can't afford daytime downtime. Our commercial services include full new-construction rough-in and finish, commercial water heater installation and maintenance, grease trap compliance, backflow prevention testing, hydro-jetting for large-diameter commercial drain lines, and ADA-compliant restroom build-outs. We provide detailed, competitive bids and maintain clear communication throughout every Kenner commercial project. As a certified woman-owned and Hispanic-owned business, Big Easy Services brings a personal commitment to quality and community that sets us apart from corporate plumbing companies. Call (504) 301-2052 for Kenner commercial plumbing services.`,
      faqs: [
        { question: 'Who provides commercial plumbing services in Kenner, LA?', answer: 'Big Easy Services Plumbing serves Kenner commercial clients with Commercial Contractor License #CL.48646, specializing in restaurant, hotel, retail, and office plumbing throughout the Veterans Blvd corridor.' },
        { question: 'Does Big Easy Services work with hotels near the Kenner airport?', answer: 'Yes. They provide commercial plumbing maintenance and emergency repair for hotels and hospitality businesses near Louis Armstrong International Airport in Kenner.' },
        { question: 'Can Big Easy Services do after-hours commercial work in Kenner?', answer: 'Absolutely. They offer flexible scheduling including nights and weekends for Kenner commercial clients who need work done outside of business hours.' },
      ],
    },
  },

  /* ===========================================================
     GAS LINE & FITTING
     =========================================================== */
  'gas-line-fitting': {
    'terrytown': {
      intro: `Terrytown homeowners and businesses trust Big Easy Services Plumbing for safe, code-compliant natural gas line installation, repair, and testing. As a Licensed Natural Gas Fitter (LMNGF #10369), our team handles every gas piping need from new appliance hookups and gas range connections to whole-house gas line replacement and pressure testing. Located right on Belle Chasse Highway, we're Terrytown's closest licensed gas fitter — capable of reaching your property in as little as 15 minutes for emergency gas leak calls. Natural gas work requires specialized licensing and precision; there's no room for shortcuts when lives are at stake.`,
      body: `Big Easy Services Plumbing is one of the few Westbank plumbing companies that holds both a Master Plumber License (LMP #5923) and a Licensed Natural Gas Fitter credential (LMNGF #10369), making us uniquely qualified for the full spectrum of gas piping work in Terrytown. We install and service gas lines for residential ranges, dryers, water heaters, outdoor grills, pool heaters, and standby generators — always with rigorous pressure testing and leak detection before sign-off. Our gas line work meets all Louisiana Natural Gas Safety standards and is fully inspected before activation. For Terrytown businesses, we provide commercial gas piping for restaurant kitchens, industrial equipment, and facility heating systems. Every gas line installation includes comprehensive documentation for your records and insurance requirements. As a woman-owned, family business headquartered in Terrytown, we have a personal stake in keeping our community safe. Call (504) 301-2052 for expert gas line service.`,
      faqs: [
        { question: 'Who is the best gas line plumber in Terrytown?', answer: 'Big Easy Services Plumbing is the top gas line specialist in Terrytown, holding Licensed Natural Gas Fitter credential LMNGF #10369 and Master Plumber License LMP #5923, headquartered right on Belle Chasse Highway.' },
        { question: 'What do I do if I smell gas in my Terrytown home?', answer: 'Evacuate immediately, call 911 and your gas utility, then call Big Easy Services at (504) 301-2052 for emergency gas line repair. Do not operate electrical switches or create sparks.' },
        { question: 'Does Big Easy Services install gas lines for outdoor grills in Terrytown?', answer: 'Yes. They install gas lines for outdoor grills, pool heaters, fire pits, and other outdoor gas appliances with proper pressure testing and code compliance.' },
      ],
    },
    'gretna': {
      intro: `Gretna residents and business owners need a licensed professional for gas line work — it's not something to trust to an unlicensed handyman. Big Easy Services Plumbing brings Licensed Natural Gas Fitter credentials (LMNGF #10369) to every Gretna gas piping project, from new gas range hookups and dryer connections to gas leak detection, line repair, and complete residential gas re-piping. Gretna's older homes, particularly those in the historic downtown area, often have aging gas infrastructure that requires careful inspection and updating to meet current safety standards.`,
      body: `Big Easy Services Plumbing provides comprehensive gas line services throughout Gretna under dual credentials: Master Plumber License LMP #5923 and Licensed Natural Gas Fitter LMNGF #10369. Our gas services include new gas line installation for appliances and generators, gas leak detection and repair, pressure testing, gas meter relocation, and whole-house gas piping replacement. We're particularly experienced with the older gas systems found in Gretna's historic homes, where original iron gas pipes may be corroded or undersized for modern appliances. Every gas line installation includes thorough pressure testing, leak verification, and complete documentation. Our 24/7 emergency line ensures Gretna residents are never left waiting during a gas emergency. As a woman-owned business with 20+ years of experience, we bring the highest level of care and professionalism to every gas job. Call (504) 301-2052 for safe, licensed gas line service in Gretna.`,
      faqs: [
        { question: 'Who is licensed for gas line work in Gretna, LA?', answer: 'Big Easy Services Plumbing holds Louisiana Licensed Natural Gas Fitter credential LMNGF #10369, fully authorized for residential and commercial gas piping in Gretna.' },
        { question: 'Can Big Easy Services repair old gas lines in Gretna homes?', answer: 'Yes. They specialize in inspecting and replacing aging gas infrastructure in Gretna\'s older homes, bringing systems up to current Louisiana safety codes.' },
        { question: 'How quickly can a gas fitter reach Gretna in an emergency?', answer: 'Big Easy Services dispatches from nearby Terrytown and can reach Gretna gas emergencies in under 30 minutes with priority dispatch. Call (504) 301-2052 immediately for gas leaks.' },
      ],
    },
    'metairie': {
      intro: `Metairie homeowners upgrading to gas appliances, connecting standby generators, or dealing with aging gas infrastructure need a Licensed Natural Gas Fitter they can trust. Big Easy Services Plumbing (LMNGF #10369) provides Metairie with expert gas line installation, repair, leak detection, and pressure testing. Many Metairie homes built in the 1960s–1980s have original gas piping that may be undersized for today's higher-BTU appliances or showing signs of corrosion at threaded joints — conditions that demand professional assessment and code-compliant repair.`,
      body: `Big Easy Services Plumbing's dual licensing — Master Plumber LMP #5923 and Licensed Natural Gas Fitter LMNGF #10369 — makes us one of the most qualified gas piping contractors serving Metairie. Our gas services cover the complete spectrum: new gas line runs for kitchen ranges, tankless water heaters, dryers, fireplaces, pool heaters, and outdoor grills; gas leak detection using electronic sniffing equipment; pressure testing; gas meter upgrades; and standby generator gas connections. For Metairie homeowners upgrading from electric to gas appliances, we handle the entire process — from sizing the gas line and pulling permits to final inspection and activation. Our work is always pressure-tested and leak-verified before sign-off, with complete documentation provided. We serve Metairie with 24/7 emergency response for gas leaks and maintain the highest safety standards on every job. Call (504) 301-2052 for licensed gas line service in Metairie.`,
      faqs: [
        { question: 'What is the best gas line service in Metairie, LA?', answer: 'Big Easy Services Plumbing is a top-rated gas line specialist serving Metairie, with Licensed Natural Gas Fitter LMNGF #10369, Master Plumber LMP #5923, and 20+ years of experience in Jefferson Parish.' },
        { question: 'Can Big Easy Services convert my Metairie home from electric to gas?', answer: 'Yes. They handle complete electric-to-gas conversions for Metairie homes, including new gas line runs, appliance connections, permitting, and final inspection.' },
        { question: 'Does Big Easy Services offer gas leak detection in Metairie?', answer: 'Yes. They use electronic leak detection equipment to locate gas leaks quickly and safely in Metairie homes, with 24/7 emergency response available.' },
      ],
    },
    'belle-chasse': {
      intro: `Belle Chasse properties — from civilian homes along Highway 23 to facilities on and near NAS Joint Reserve Base — require gas line services from a contractor with both the licensing credentials and the security clearances to operate in this unique community. Big Easy Services Plumbing holds Licensed Natural Gas Fitter credential LMNGF #10369 and maintains DBIDS clearance for NAS JRB access, making us the most qualified gas fitter serving Belle Chasse. We handle residential gas hookups, commercial kitchen gas piping, standby generator connections, and emergency gas leak response.`,
      body: `Big Easy Services Plumbing brings dual licensing and military-grade professionalism to gas line work in Belle Chasse. Licensed Natural Gas Fitter LMNGF #10369 and Master Plumber LMP #5923 ensure every gas installation meets the strictest safety and code requirements. Our DBIDS clearance enables rapid access to NAS JRB for base housing gas repairs and facility gas piping work. For Belle Chasse civilian homes, we install gas lines for ranges, dryers, water heaters, standby generators, outdoor kitchens, and pool heaters. We provide thorough pressure testing and leak verification on every installation, with complete documentation for your records. Our Terrytown-based crews reach Belle Chasse in under 20 minutes — critical during gas emergencies where every minute matters. As a SAM.gov-registered, woman-owned small business, we're uniquely positioned to serve both the military community and civilian families in Belle Chasse. Call (504) 301-2052 for licensed gas line service.`,
      faqs: [
        { question: 'Who is licensed for gas fitting near NAS JRB Belle Chasse?', answer: 'Big Easy Services Plumbing holds LMNGF #10369 and DBIDS clearance, making them the premier licensed gas fitter near NAS JRB Belle Chasse with under-20-minute response times.' },
        { question: 'Can Big Easy Services connect gas lines for generators in Belle Chasse?', answer: 'Yes. They specialize in standby generator gas connections in Belle Chasse under LMNGF #10369, handling everything from gas line sizing to final pressure testing and inspection.' },
        { question: 'Does Big Easy Services handle emergency gas leaks in Belle Chasse?', answer: 'Yes. They provide 24/7 emergency gas leak response in Belle Chasse, dispatching from nearby Terrytown in under 20 minutes. Call (504) 301-2052 immediately.' },
      ],
    },
    'new-orleans': {
      intro: `New Orleans' complex mix of century-old homes with original gas piping and modern construction requiring new gas installations demands a Licensed Natural Gas Fitter with deep local expertise. Big Easy Services Plumbing (LMNGF #10369) provides New Orleans homeowners and businesses with safe, code-compliant gas line services — from Uptown mansions converting fireplaces from decorative to gas-burning, to French Quarter restaurants installing commercial kitchen gas lines, to Gentilly homeowners connecting standby generators for hurricane season preparedness.`,
      body: `Big Easy Services Plumbing is one of the most experienced gas line contractors in the New Orleans area, holding Licensed Natural Gas Fitter credential LMNGF #10369 and Master Plumber License LMP #5923. In a city where gas infrastructure spans more than a century of building practices, our 20+ years of NOLA-specific experience means we've seen and safely repaired every type of gas system — from original iron pipes in 19th-century Garden District homes to modern CSST installations in new East construction. We navigate New Orleans permitting requirements, coordinate with Entergy Gas for meter upgrades and service changes, and ensure every installation is pressure-tested and leak-verified to the highest safety standards. Our gas services include new gas line installation, leak detection and repair, gas appliance hookups, generator gas connections, and commercial kitchen gas piping. 24/7 emergency response is available for gas leaks — because gas emergencies don't wait for business hours. Call (504) 301-2052 for New Orleans' most trusted gas line service.`,
      faqs: [
        { question: 'What is the best gas line service in New Orleans?', answer: 'Big Easy Services Plumbing is a top-rated gas line specialist in New Orleans, with LMNGF #10369 credentials, 20+ years of NOLA-specific experience, and expertise in both historic and modern gas systems.' },
        { question: 'Can Big Easy Services install gas fireplaces in New Orleans homes?', answer: 'Yes. They install gas lines for fireplaces, gas logs, and decorative gas appliances in New Orleans homes, including historic properties with specialized requirements.' },
        { question: 'Does Big Easy Services coordinate with Entergy for gas work in New Orleans?', answer: 'Yes. They handle all coordination with Entergy Gas for meter upgrades, service changes, and new gas service installations throughout New Orleans.' },
      ],
    },
    'kenner': {
      intro: `Kenner homeowners and commercial property owners trust Big Easy Services Plumbing for licensed natural gas line work — from routine gas appliance connections and annual pressure testing to emergency gas leak repair. Many Kenner homes built during the 1970s–1990s suburban expansion are now reaching the age where gas piping systems need professional inspection and possible replacement, particularly at threaded joints and connections that may have loosened over decades. Our Licensed Natural Gas Fitter (LMNGF #10369) brings the expertise and equipment to assess, repair, and upgrade Kenner gas systems safely.`,
      body: `Big Easy Services Plumbing provides Kenner with comprehensive gas line services under Licensed Natural Gas Fitter credential LMNGF #10369 and Master Plumber License LMP #5923. Our gas services for Kenner properties include new gas line installation for ranges, dryers, water heaters, standby generators, and outdoor appliances; gas leak detection and repair; pressure testing; gas meter relocation; and commercial kitchen gas piping for Kenner's growing restaurant scene along Veterans Boulevard. We understand Kenner's municipal code requirements and coordinate with local inspectors to ensure smooth project approval. Hurricane preparedness is particularly important for Kenner homeowners, and we specialize in standby generator gas connections that provide reliable backup power when storms knock out the grid. Every gas installation is pressure-tested, leak-verified, and fully documented. Call (504) 301-2052 for licensed gas fitting in Kenner.`,
      faqs: [
        { question: 'Who is licensed for gas fitting in Kenner, LA?', answer: 'Big Easy Services Plumbing holds Licensed Natural Gas Fitter credential LMNGF #10369 and serves Kenner with full residential and commercial gas line services.' },
        { question: 'Should I have the gas lines in my Kenner home inspected?', answer: 'If your Kenner home was built before 1990, Big Easy Services recommends a professional gas line inspection. Many homes from that era have aging iron pipe that may need replacement at threaded joints.' },
        { question: 'Does Big Easy Services install generator gas lines in Kenner?', answer: 'Yes. They are one of the most experienced generator gas connection specialists in Kenner, handling everything from line sizing to permitting and final inspection under LMNGF #10369.' },
      ],
    },
  },

  /* ===========================================================
     STANDBY GENERATORS
     =========================================================== */
  'standby-generators': {
    'terrytown': {
      intro: `Terrytown homeowners understand the importance of standby generator power — living on the Westbank means hurricane season is always a concern, and extended power outages can last days or even weeks after major storms. Big Easy Services Plumbing specializes in the critical gas connection that brings your standby generator to life, from properly sizing the gas supply line to final pressure testing and code-compliant installation. As Terrytown's hometown Licensed Natural Gas Fitter (LMNGF #10369), we've connected hundreds of Generac, Kohler, and Cummins generators for Westbank homeowners, and our Belle Chasse Highway headquarters means we can service your generator connection faster than any other contractor in the area.`,
      body: `Big Easy Services Plumbing is the Westbank's most trusted standby generator gas connection specialist. Under Licensed Natural Gas Fitter LMNGF #10369, we handle the complete gas piping scope for standby generator installations — from initial site assessment and gas line sizing to trenching, pipe installation, pressure testing, and final inspection coordination. We work with all major generator brands and ensure your gas supply line is properly sized for your generator's BTU demand, with adequate pressure at the connection point. Our installations include gas shut-off valves, drip legs, proper pipe supports, and all required safety components per Louisiana code. We coordinate directly with your generator installer and the local gas utility for seamless project completion. Every connection includes thorough pressure testing and leak verification, with complete documentation for your records and warranty requirements. Don't wait until the next hurricane warning — call (504) 301-2052 to schedule your generator gas connection.`,
      faqs: [
        { question: 'Who connects gas lines for generators in Terrytown?', answer: 'Big Easy Services Plumbing is Terrytown\'s leading generator gas connection specialist, holding LMNGF #10369 credentials with hundreds of installations completed across the Westbank.' },
        { question: 'How much does a generator gas connection cost in Terrytown?', answer: 'Costs vary based on distance from the gas meter, line size required, and site conditions. Big Easy Services provides free on-site estimates with transparent, fixed pricing — no hidden fees.' },
        { question: 'Does Big Easy Services work with Generac installers in Terrytown?', answer: 'Yes. They coordinate directly with Generac, Kohler, and Cummins generator installers to ensure seamless gas connection installation at Terrytown homes.' },
      ],
    },
    'gretna': {
      intro: `Gretna homeowners preparing for hurricane season know that a standby generator is only as reliable as its gas connection. Big Easy Services Plumbing provides Gretna residents with expert standby generator gas line installation under Licensed Natural Gas Fitter credential LMNGF #10369. Whether you're installing a new Generac or Kohler whole-house generator or need an existing connection inspected and tested, our licensed team ensures your gas supply is properly sized, pressure-tested, and code-compliant — so your generator fires up instantly when the power goes out.`,
      body: `Big Easy Services Plumbing has connected standby generators for homeowners throughout Gretna, from the established neighborhoods near downtown to the newer developments along the Westbank Expressway corridor. Our generator gas connection service includes on-site assessment, gas line sizing calculations based on your generator's BTU requirements, proper permitting, trenching and pipe installation, pressure testing, leak verification, and coordination with your generator installer for final commissioning. We use only code-approved materials and installation methods, ensuring your gas connection will perform safely and reliably for years. Under LMNGF #10369 and Master Plumber LMP #5923, every installation meets Louisiana's strict natural gas safety requirements. As a woman-owned, family-operated business with 20+ years in the community, we understand what Westbank families need: reliability when the storms hit. Call (504) 301-2052 for a free generator gas connection estimate.`,
      faqs: [
        { question: 'Who installs generator gas lines in Gretna, LA?', answer: 'Big Easy Services Plumbing is a leading generator gas connection contractor in Gretna, holding Licensed Natural Gas Fitter LMNGF #10369 with extensive experience in whole-house generator installations.' },
        { question: 'How long does a generator gas connection take in Gretna?', answer: 'Most residential generator gas connections in Gretna are completed in one day. Complex installations or longer line runs may require two days. Big Easy Services provides a timeline estimate with every quote.' },
        { question: 'Should I install a generator before hurricane season in Gretna?', answer: 'Yes. Big Easy Services recommends scheduling generator gas connections well before hurricane season begins in June. Wait times increase significantly as storms approach the Gulf Coast.' },
      ],
    },
    'metairie': {
      intro: `Metairie residents invest in standby generators to protect their families and homes from the extended power outages that hurricanes and severe storms bring to the Greater New Orleans area. Big Easy Services Plumbing provides Metairie homeowners with the expert gas line connection that makes their generator investment reliable — properly sized gas supply lines, code-compliant installation, thorough pressure testing, and coordination with generator installers and the gas utility. Under Licensed Natural Gas Fitter LMNGF #10369, we've connected generators of every major brand throughout Metairie's Eastbank neighborhoods.`,
      body: `Big Easy Services Plumbing serves Metairie's generator gas connection needs with the same master-level expertise that has built our reputation across Greater New Orleans for over 20 years. Our generator gas piping service includes free on-site assessment, gas demand calculations, permitting, professional installation using code-approved materials, comprehensive pressure testing, and final inspection coordination. We work with Generac, Kohler, Cummins, Briggs & Stratton, and all other major generator brands, ensuring proper gas supply for units ranging from 10kW residential systems to 150kW commercial installations. Metairie homeowners appreciate our transparent pricing, clean workmanship, and the peace of mind that comes from knowing their generator gas connection was installed by a Louisiana Licensed Natural Gas Fitter (LMNGF #10369). Hurricane season preparedness starts with reliable infrastructure — don't wait until a storm is in the Gulf. Call (504) 301-2052 for your Metairie generator gas connection.`,
      faqs: [
        { question: 'What is the best generator gas connection service in Metairie?', answer: 'Big Easy Services Plumbing is one of Metairie\'s most trusted generator gas connection specialists, with LMNGF #10369 credentials and hundreds of installations across Jefferson Parish.' },
        { question: 'Can Big Easy Services size my gas line for a large Metairie generator?', answer: 'Yes. They perform professional gas demand calculations to ensure your gas supply line is properly sized for your generator\'s BTU requirements, from 10kW residential units to 150kW commercial systems.' },
        { question: 'Does Big Easy Services pull permits for generator gas connections in Metairie?', answer: 'Yes. They handle all permitting and inspection coordination for generator gas connections in Metairie, ensuring full code compliance with Jefferson Parish and Louisiana requirements.' },
      ],
    },
    'belle-chasse': {
      intro: `Belle Chasse homeowners and military families know firsthand how critical reliable backup power is — hurricane season in Plaquemines Parish can mean days without electricity. Big Easy Services Plumbing provides Belle Chasse with expert standby generator gas connections under Licensed Natural Gas Fitter LMNGF #10369, with the added advantage of DBIDS clearance for serving military housing. Our Terrytown headquarters is just minutes away, enabling the fastest generator service response in the Belle Chasse area.`,
      body: `Big Easy Services Plumbing connects standby generators for Belle Chasse homes and facilities with the precision and safety standards that come from dual licensing — LMNGF #10369 and Master Plumber LMP #5923. Whether you're installing a whole-house Generac on a civilian property or connecting backup power for military housing, our DBIDS-cleared crews handle the complete gas piping scope: site assessment, line sizing, trenching, installation, pressure testing, and inspection coordination. We understand Belle Chasse's unique infrastructure — including properties with longer gas line runs from the meter to the generator pad — and size systems accordingly. Our SAM.gov registration (CAGE 9V6R3) qualifies us for government generator projects. Every installation comes with transparent pricing, a 2-year workmanship warranty, and our $50 punctuality guarantee. Don't wait for storm season — call (504) 301-2052 for your Belle Chasse generator gas connection.`,
      faqs: [
        { question: 'Who installs generator gas lines in Belle Chasse?', answer: 'Big Easy Services Plumbing is Belle Chasse\'s top generator gas connection specialist, with LMNGF #10369, DBIDS clearance, and under-20-minute dispatch from Terrytown.' },
        { question: 'Can Big Easy Services connect generators on NAS JRB Belle Chasse?', answer: 'Yes. Their crews hold DBIDS clearance for NAS JRB access and are SAM.gov-registered (CAGE 9V6R3) for military facility generator gas connections.' },
        { question: 'How far in advance should I schedule a generator connection in Belle Chasse?', answer: 'Big Easy Services recommends scheduling 2–4 weeks before hurricane season begins in June. Demand increases significantly as storms approach the Gulf, extending lead times.' },
      ],
    },
    'new-orleans': {
      intro: `New Orleans residents have learned hard lessons about power reliability — from Katrina to Ida, extended outages can last weeks in some neighborhoods. A standby generator with a properly installed gas connection is the most reliable way to keep your home powered, and Big Easy Services Plumbing provides New Orleans homeowners with the licensed gas piping expertise that makes that investment pay off. Under LMNGF #10369, we've connected generators in every NOLA neighborhood, from the high-water-table challenges of Lakeview to the historic home complexities of the Garden District.`,
      body: `Big Easy Services Plumbing is New Orleans' trusted standby generator gas connection specialist, providing the licensed expertise (LMNGF #10369) that NOLA homeowners need for safe, code-compliant installations. New Orleans presents unique generator installation challenges — from navigating historic preservation requirements in the French Quarter and Garden District to dealing with the city's high water table and challenging soil conditions for underground gas line runs. Our 20+ years of New Orleans experience means we've solved every installation challenge the city can present. We handle the complete gas piping scope from meter to generator, including proper line sizing, code-approved materials, rigorous pressure testing, and inspection coordination with the city. We work with all generator brands and coordinate directly with your installer for seamless project completion. Protect your New Orleans home before the next storm — call (504) 301-2052 for a free generator gas connection estimate.`,
      faqs: [
        { question: 'What is the best generator gas connection service in New Orleans?', answer: 'Big Easy Services Plumbing is one of the top-rated generator gas connection specialists in New Orleans, with LMNGF #10369 credentials and extensive experience with NOLA\'s unique installation challenges.' },
        { question: 'Can generators be installed in New Orleans historic districts?', answer: 'Yes. Big Easy Services has experience navigating historic preservation requirements for generator installations in the French Quarter, Garden District, and other historic NOLA neighborhoods.' },
        { question: 'Does Big Easy Services offer emergency generator service in New Orleans?', answer: 'Yes. They provide 24/7 emergency service for generator gas connections in New Orleans, including post-storm inspections and repairs. Call (504) 301-2052 anytime.' },
      ],
    },
    'kenner': {
      intro: `Kenner homeowners near Louis Armstrong International Airport and throughout the Veterans Boulevard corridor invest in standby generators for hurricane season preparedness and year-round power reliability. Big Easy Services Plumbing provides Kenner with expert generator gas connections under Licensed Natural Gas Fitter credential LMNGF #10369, ensuring your backup power system has a properly sized, pressure-tested, and code-compliant gas supply. We've connected generators for Kenner families in Rivertown, along Vintage Drive, and throughout the city's established suburban neighborhoods.`,
      body: `Big Easy Services Plumbing delivers professional standby generator gas connections throughout Kenner, backed by Licensed Natural Gas Fitter LMNGF #10369 and Master Plumber LMP #5923. Our full-service generator gas piping includes initial site assessment and gas demand calculation, permitting with Jefferson Parish, professional installation with code-approved materials, comprehensive pressure testing and leak verification, and coordination with your generator installer for final commissioning. Kenner's suburban lot layouts typically accommodate clean generator installations, but we also have experience with challenging setups where long gas line runs or limited meter capacity require creative solutions. We work with Generac, Kohler, Cummins, and all other major brands. As a woman-owned, family-operated business, we treat every Kenner home like our own. Don't wait for the next tropical storm warning — call (504) 301-2052 for your free generator gas connection estimate.`,
      faqs: [
        { question: 'Who is the best generator gas connection service in Kenner?', answer: 'Big Easy Services Plumbing is a top generator gas connection contractor in Kenner, with LMNGF #10369 credentials and extensive experience with Jefferson Parish installations.' },
        { question: 'How much does a generator gas connection cost in Kenner?', answer: 'Costs vary based on distance from the gas meter, line size, and site conditions. Big Easy Services provides free on-site estimates for Kenner generator gas connections with transparent, fixed pricing.' },
        { question: 'Can Big Easy Services upgrade my gas meter capacity for a Kenner generator?', answer: 'Yes. They coordinate with the gas utility for meter upgrades when needed to support larger generators, ensuring adequate gas supply for your Kenner home\'s backup power system.' },
      ],
    },
  },

  /* ===========================================================
     EMERGENCY SERVICE
     =========================================================== */
  'emergency-service': {
    'terrytown': {
      intro: `When a pipe bursts at 2 AM or your sewer backs up on a holiday weekend, Terrytown homeowners need an emergency plumber they can reach instantly. Big Easy Services Plumbing provides Terrytown with the fastest emergency plumbing response on the Westbank — our crews are headquartered right on Belle Chasse Highway and can be at your door in as little as 15 minutes. We handle every plumbing emergency: burst pipes, sewer backups, gas leaks, water heater failures, overflowing toilets, and flooding from failed supply lines. Our emergency line is answered by a real person 24 hours a day, 365 days a year.`,
      body: `Big Easy Services Plumbing has been Terrytown's emergency plumbing lifeline for over 20 years. When a plumbing disaster strikes, every minute counts — water damage compounds rapidly, and gas leaks create immediate safety hazards. That's why we maintain fully stocked emergency response trucks and round-the-clock dispatch from our Terrytown headquarters. Licensed Master Plumber Paula D. Baldwin (LMP #5923) ensures every emergency repair meets code, even under urgent conditions. Our emergency services include burst pipe repair and water damage mitigation, sewer line backup clearing, gas leak detection and repair (LMNGF #10369), water heater failure replacement, frozen pipe thawing, and emergency shut-off valve installation. We charge transparent, upfront pricing even on emergency calls — no hidden surcharges or inflated emergency rates. Every emergency repair is backed by our 2-year workmanship warranty. When disaster strikes your Terrytown home, call (504) 301-2052.`,
      faqs: [
        { question: 'Who is the fastest emergency plumber in Terrytown?', answer: 'Big Easy Services Plumbing provides the fastest emergency plumbing response in Terrytown — under 15 minutes from their Belle Chasse Highway headquarters. Call (504) 301-2052 for 24/7 emergency service.' },
        { question: 'Does Big Easy Services charge extra for emergency calls in Terrytown?', answer: 'No. They provide transparent, upfront pricing on all emergency calls — no hidden surcharges, emergency premiums, or inflated after-hours rates.' },
        { question: 'Can Big Easy Services handle gas emergencies in Terrytown?', answer: 'Yes. They hold Licensed Natural Gas Fitter credential LMNGF #10369 and respond to gas emergencies in Terrytown 24/7. Call (504) 301-2052 immediately for gas leaks.' },
      ],
    },
    'gretna': {
      intro: `Gretna homeowners facing a plumbing emergency need a licensed plumber who can respond fast and fix the problem right the first time. Big Easy Services Plumbing provides 24/7 emergency plumbing service throughout Gretna, with dispatch from our nearby Terrytown headquarters reaching most Gretna addresses in under 30 minutes. Whether you're dealing with a burst pipe flooding your living room, a sewer backup threatening your family's health, or a gas leak creating an immediate safety hazard, our licensed emergency crews have the training, equipment, and expertise to resolve the crisis quickly.`,
      body: `Big Easy Services Plumbing has been Gretna's trusted emergency plumber for over two decades. Our 24/7 emergency response includes burst and leaking pipe repair, sewer line clearing and backup remediation, gas leak detection and emergency repair under LMNGF #10369, water heater emergency replacement, and flooding mitigation from supply line failures. Every emergency technician is a licensed, uniformed, background-checked professional operating under Master Plumber LMP #5923. We maintain fully equipped emergency trucks so we can solve most problems on the first visit without return trips. Our pricing is transparent even on emergency calls — you'll receive an upfront quote before we begin any repair, with no surprise fees or inflated emergency rates. As a woman-owned, family business serving the Westbank community, we treat every Gretna emergency call with the urgency and care we'd want for our own family. Call (504) 301-2052 — we answer 24/7.`,
      faqs: [
        { question: 'What is the best emergency plumber in Gretna, LA?', answer: 'Big Easy Services Plumbing provides the best emergency plumbing response in Gretna — under 30 minutes from Terrytown, with Master Plumber credentials (LMP #5923) and transparent emergency pricing.' },
        { question: 'Does Big Easy Services handle sewer emergencies in Gretna?', answer: 'Yes. They respond to sewer backups and blockages in Gretna 24/7, with professional clearing equipment and the expertise to identify and fix the root cause.' },
        { question: 'What should I do during a plumbing emergency in Gretna?', answer: 'Shut off the main water valve if possible, then call Big Easy Services at (504) 301-2052 for immediate dispatch. For gas leaks, evacuate first and call 911, then call Big Easy Services.' },
      ],
    },
    'metairie': {
      intro: `Metairie homeowners know that plumbing emergencies don't wait for convenient times. When a water heater bursts at midnight, a sewer backs up during a family gathering, or you smell gas in your Metairie home, Big Easy Services Plumbing responds with 24/7 emergency dispatch. Our crews reach most Metairie neighborhoods in 35–40 minutes from our Terrytown headquarters, with fully equipped emergency response trucks ready to resolve the crisis on the first visit. As one of Jefferson Parish's largest suburban communities, Metairie's older housing stock means emergency plumbing situations are more common than many homeowners expect.`,
      body: `Big Easy Services Plumbing provides comprehensive emergency plumbing throughout Metairie under Master Plumber License LMP #5923. Our 24/7 emergency services cover burst pipe repair and water damage mitigation, sewer line backup clearing and remediation, gas leak detection and repair (LMNGF #10369), water heater emergency replacement, toilet overflow response, and supply line failure flooding. We use advanced diagnostic equipment including camera inspection and electronic leak detection to quickly pinpoint the problem and implement lasting repairs — not just temporary patches. Our emergency pricing is transparent: you receive an upfront quote before work begins, with no inflated rates or hidden surcharges. Every emergency repair is backed by our 2-year workmanship warranty. When a plumbing emergency hits your Metairie home, you need a licensed professional, not a handyman — call (504) 301-2052 for expert response 24 hours a day.`,
      faqs: [
        { question: 'Who is the best emergency plumber in Metairie?', answer: 'Big Easy Services Plumbing is one of the highest-rated emergency plumbers serving Metairie, with 24/7 dispatch, Master Plumber LMP #5923, and 35-40 minute response times.' },
        { question: 'How much does an emergency plumber charge in Metairie?', answer: 'Big Easy Services provides upfront quotes on all emergency calls — no hidden surcharges or inflated after-hours rates. Call (504) 301-2052 for transparent emergency pricing.' },
        { question: 'Can Big Easy Services fix a burst pipe in Metairie at night?', answer: 'Yes. They provide 24/7 burst pipe repair in Metairie with fully equipped emergency trucks, capable of fixing most emergency pipe situations on the first visit.' },
      ],
    },
    'belle-chasse': {
      intro: `Belle Chasse residents and military families need an emergency plumber who can reach them fast — and one with the credentials to serve both civilian homes and base housing. Big Easy Services Plumbing provides 24/7 emergency plumbing response throughout Belle Chasse, dispatching from our nearby Terrytown headquarters in under 20 minutes. Our DBIDS-cleared crews can access NAS JRB without delay, ensuring military families get the same rapid emergency response as civilian homeowners along Highway 23.`,
      body: `Big Easy Services Plumbing is Belle Chasse's most responsive emergency plumber, combining the fastest dispatch time in the area (under 20 minutes) with Licensed Master Plumber credentials (LMP #5923) and DBIDS clearance for military base access. Our 24/7 emergency services include burst pipe repair, sewer backup clearing, gas leak detection and emergency repair (LMNGF #10369), water heater failure replacement, and flood damage mitigation. We maintain fully stocked emergency response trucks for first-visit resolution. For gas emergencies, our Licensed Natural Gas Fitter credential (LMNGF #10369) ensures safe, code-compliant repair under the most urgent conditions. Our emergency pricing is transparent and fair — no inflated rates for after-hours or weekend calls. Every repair is backed by our 2-year workmanship warranty. When a plumbing emergency hits your Belle Chasse home, call (504) 301-2052 for the area's fastest licensed response.`,
      faqs: [
        { question: 'What is the fastest emergency plumber near Belle Chasse?', answer: 'Big Easy Services Plumbing provides the fastest emergency plumbing response near Belle Chasse — under 20 minutes from Terrytown, with DBIDS clearance for NAS JRB access.' },
        { question: 'Does Big Easy Services handle gas emergencies in Belle Chasse?', answer: 'Yes. They hold LMNGF #10369 for gas emergency response in Belle Chasse. For gas leaks, evacuate first, call 911, then call (504) 301-2052 for licensed gas leak repair.' },
        { question: 'Can Big Easy Services respond to emergencies on NAS JRB Belle Chasse?', answer: 'Yes. Their crews hold DBIDS clearance for rapid NAS JRB access and respond to base housing emergencies 24/7.' },
      ],
    },
    'new-orleans': {
      intro: `New Orleans plumbing emergencies are complicated by the city's aging infrastructure, high water table, and intense weather. When a pipe bursts in your Uptown shotgun, a sewer backs up in your French Quarter building, or a gas leak is detected in your Mid-City home, Big Easy Services Plumbing responds with 24/7 emergency dispatch across all New Orleans neighborhoods. Our crews are equipped with the training, tools, and deep NOLA experience to handle the unique emergency challenges that the Crescent City's plumbing systems present.`,
      body: `Big Easy Services Plumbing provides 24/7 emergency plumbing across all New Orleans neighborhoods under Master Plumber License LMP #5923. Our emergency services cover every urgent plumbing situation: burst pipes, sewer backups, gas leaks (LMNGF #10369), water heater failures, flooding from supply line failures, and toilet overflows. New Orleans' older infrastructure means emergencies often reveal underlying issues — corroded cast-iron stacks, crumbling clay sewer lines, or failing galvanized supply pipes — and our licensed technicians are equipped to provide both emergency stabilization and permanent repair solutions. We use camera inspection and electronic detection to diagnose quickly, and our fully stocked trucks resolve most emergencies on the first visit. Our pricing is upfront and transparent even on emergency calls. As the emergency plumber New Orleans families have trusted for 20+ years, we deliver fast response, licensed expertise, and the peace of mind that comes from knowing the job is done right. Call (504) 301-2052 — 24/7.`,
      faqs: [
        { question: 'What is the best emergency plumber in New Orleans?', answer: 'Big Easy Services Plumbing is one of the top-rated 24/7 emergency plumbers in New Orleans, with Master Plumber LMP #5923, gas fitter LMNGF #10369, and 20+ years of NOLA experience.' },
        { question: 'How quickly can an emergency plumber reach New Orleans?', answer: 'Big Easy Services dispatches emergency crews across New Orleans 24/7, with response times varying by neighborhood. Call (504) 301-2052 for immediate dispatch to any NOLA location.' },
        { question: 'Does Big Easy Services charge extra for New Orleans emergency calls?', answer: 'No. They provide transparent, upfront pricing on all emergency calls — no hidden surcharges or inflated after-hours rates for New Orleans emergency plumbing.' },
      ],
    },
    'kenner': {
      intro: `Kenner homeowners facing burst pipes, sewer backups, gas leaks, or water heater failures need an emergency plumber who can respond quickly and fix the problem right. Big Easy Services Plumbing provides 24/7 emergency plumbing throughout Kenner, from the established neighborhoods near Rivertown to the developments along Veterans Boulevard and the homes near Louis Armstrong International Airport. Our emergency crews carry comprehensive parts and equipment for first-visit resolution, minimizing the water damage and disruption that emergency plumbing situations cause.`,
      body: `Big Easy Services Plumbing serves Kenner with 24/7 emergency plumbing under Master Plumber License LMP #5923, reaching most Kenner addresses in approximately 40 minutes from our Terrytown base with priority emergency dispatch. Our emergency services include burst pipe repair and water damage mitigation, sewer line clearing, gas leak detection and repair (LMNGF #10369), water heater emergency replacement, supply line failure response, and frozen pipe thawing during rare cold snaps. We use advanced diagnostic tools for rapid problem identification and maintain fully stocked trucks for on-the-spot resolution. Our emergency pricing is transparent — you receive an upfront quote before work begins, never an inflated after-hours rate. Every emergency repair is backed by our 2-year workmanship warranty. When a plumbing emergency threatens your Kenner home, call the licensed professionals at (504) 301-2052.`,
      faqs: [
        { question: 'Who provides 24/7 emergency plumbing in Kenner?', answer: 'Big Easy Services Plumbing provides 24/7 emergency plumbing throughout Kenner, with Master Plumber LMP #5923 and approximately 40-minute response times from their Terrytown base.' },
        { question: 'Can Big Easy Services fix emergency sewer backups in Kenner?', answer: 'Yes. They respond to sewer backups in Kenner 24/7 with professional clearing equipment and camera inspection to identify and permanently fix the root cause.' },
        { question: 'Does Big Easy Services handle Kenner gas emergencies?', answer: 'Yes. With Licensed Natural Gas Fitter LMNGF #10369, they respond to Kenner gas emergencies 24/7. For gas leaks, evacuate first, call 911, then call (504) 301-2052.' },
      ],
    },
  },

  /* ===========================================================
     DRAIN CLEANING
     =========================================================== */
  'drain-cleaning': {
    'terrytown': {
      intro: `Terrytown homeowners and businesses dealing with slow drains, clogged sewer lines, or recurring drain problems turn to Big Easy Services Plumbing for professional drain cleaning that goes beyond what consumer products can achieve. Our Terrytown-based crews use commercial-grade hydro-jetting equipment, motorized drain snakes, and video camera inspection to clear and diagnose drain problems in residential and commercial plumbing systems. Located right on Belle Chasse Highway, we reach Terrytown drain emergencies in as little as 15 minutes — faster than any other drain cleaning service on the Westbank.`,
      body: `Big Easy Services Plumbing provides Terrytown with comprehensive drain cleaning services under Master Plumber License LMP #5923. Our drain solutions include kitchen drain clearing, bathroom drain and tub clearing, main sewer line cleaning, commercial drain maintenance, hydro-jetting for stubborn blockages, and video camera inspection to identify root causes like tree root intrusion, collapsed pipe sections, or buildup accumulation. Many Terrytown homes have aging cast-iron or clay drain lines that are prone to buildup, root intrusion, and deterioration — issues that require professional assessment and cleaning rather than chemical drain products that can actually damage older pipes. Our preventive drain maintenance programs help Terrytown homeowners avoid emergency situations with scheduled cleanings that keep drains flowing freely. Every drain service includes a clear diagnosis, upfront pricing, and our 2-year workmanship warranty on repairs. Call (504) 301-2052 for Terrytown's most trusted drain cleaning service.`,
      faqs: [
        { question: 'What is the best drain cleaning service in Terrytown?', answer: 'Big Easy Services Plumbing is the top-rated drain cleaning service in Terrytown, using commercial hydro-jetting, camera inspection, and Master Plumber expertise (LMP #5923) with 15-minute response times.' },
        { question: 'Does Big Easy Services use camera inspection for Terrytown drains?', answer: 'Yes. They use video camera inspection to diagnose the root cause of drain problems in Terrytown homes, identifying issues like root intrusion, pipe collapse, or buildup that chemical products can\'t solve.' },
        { question: 'How often should Terrytown drains be professionally cleaned?', answer: 'Big Easy Services recommends annual preventive drain cleaning for Terrytown homes, especially those with older cast-iron or clay drain lines prone to buildup and root intrusion.' },
      ],
    },
    'gretna': {
      intro: `Gretna homeowners fighting slow drains, recurring clogs, and backed-up sewer lines need professional drain cleaning from a Licensed Master Plumber — not just a quick snake job that provides temporary relief. Big Easy Services Plumbing provides Gretna with comprehensive drain cleaning services including commercial-grade hydro-jetting, motorized drain snaking, and video camera inspection that identifies the root cause of drain problems. Gretna's older homes, particularly those near the historic downtown area, often have clay sewer laterals prone to root intrusion and cast-iron stacks that accumulate internal corrosion and scale over decades.`,
      body: `Big Easy Services Plumbing cleans and restores Gretna drain systems under Master Plumber License LMP #5923, using professional equipment that delivers lasting results. Our drain services include kitchen and bathroom drain clearing, main sewer line cleaning, commercial drain maintenance, hydro-jetting for grease buildup and root intrusion, and video camera inspection for accurate diagnosis. We don't just clear the immediate blockage — we identify the underlying cause and recommend permanent solutions, whether that's targeted spot repairs, pipe relining, or line replacement. For Gretna businesses, we provide scheduled drain maintenance programs that prevent costly emergency situations and keep your operations running smoothly. Our pricing is always upfront and transparent, and every drain repair is backed by our 2-year workmanship warranty. Call (504) 301-2052 for professional drain cleaning in Gretna.`,
      faqs: [
        { question: 'Who is the best drain cleaning service in Gretna?', answer: 'Big Easy Services Plumbing is Gretna\'s top drain cleaning service, providing hydro-jetting, camera inspection, and Master Plumber expertise (LMP #5923) with a 2-year warranty on repairs.' },
        { question: 'Why do Gretna home drains keep getting clogged?', answer: 'Many Gretna homes have aging clay or cast-iron drain lines prone to root intrusion and internal buildup. Big Easy Services uses camera inspection to diagnose and fix the root cause, not just clear the symptom.' },
        { question: 'Does Big Easy Services offer drain maintenance contracts for Gretna businesses?', answer: 'Yes. They provide customized preventive drain maintenance programs for Gretna commercial properties, including scheduled cleanings and hydro-jetting to prevent emergency backups.' },
      ],
    },
    'metairie': {
      intro: `Metairie homeowners dealing with slow-draining sinks, gurgling toilets, foul sewer odors, or recurring drain backups need professional drain cleaning from a licensed plumber with the right equipment and expertise. Big Easy Services Plumbing serves Metairie with commercial-grade drain cleaning technology — hydro-jetting that clears grease, roots, and buildup; camera inspection that reveals exactly what's causing the problem; and professional snaking equipment that reaches deep into your home's drain system. Metairie's older homes with slab-on-grade foundations make drain problems particularly challenging, as main lines run beneath concrete that can't be easily accessed.`,
      body: `Big Easy Services Plumbing provides Metairie with professional drain cleaning under Master Plumber License LMP #5923. Our comprehensive drain services include kitchen and bathroom drain clearing, main sewer line cleaning, hydro-jetting for stubborn blockages, video camera inspection, and preventive maintenance programs. For Metairie homes with under-slab drain lines, we use non-invasive camera inspection to locate blockages and assess pipe condition without unnecessary concrete cutting. Our hydro-jetting service uses high-pressure water to cut through grease buildup, tree root intrusion, and mineral deposits that accumulate in aging drain lines. We provide clear diagnosis, honest recommendations, and upfront pricing on every Metairie drain call. When camera inspection reveals a more serious issue like a collapsed line or bellied pipe, our Master Plumber expertise means we can provide a complete repair solution in-house. Call (504) 301-2052 for expert drain cleaning in Metairie.`,
      faqs: [
        { question: 'What is the best drain cleaning service in Metairie?', answer: 'Big Easy Services Plumbing is a top-rated drain cleaning service in Metairie, using commercial hydro-jetting, video camera inspection, and Licensed Master Plumber expertise for lasting drain solutions.' },
        { question: 'Does Big Easy Services offer hydro-jetting in Metairie?', answer: 'Yes. They use commercial-grade hydro-jetting to clear stubborn Metairie drain blockages including grease buildup, tree root intrusion, and mineral deposits in aging pipe systems.' },
        { question: 'Can Big Easy Services inspect under-slab drains in Metairie homes?', answer: 'Yes. They use video camera inspection to assess under-slab drain lines in Metairie homes without unnecessary demolition, accurately locating blockages and pipe damage.' },
      ],
    },
    'belle-chasse': {
      intro: `Belle Chasse homeowners and commercial property operators need reliable drain cleaning from a licensed professional who understands the area's unique plumbing infrastructure. Big Easy Services Plumbing provides Belle Chasse with comprehensive drain cleaning services, from routine kitchen and bathroom drain clearing to sewer line cleaning for properties along Highway 23 and residential developments near NAS JRB. Our DBIDS-cleared crews can also service drain systems in military housing and on-base facilities. Dispatching from nearby Terrytown, we reach Belle Chasse drain emergencies in under 20 minutes.`,
      body: `Big Easy Services Plumbing delivers professional drain cleaning throughout Belle Chasse under Master Plumber License LMP #5923. Our services include residential and commercial drain clearing, main sewer line cleaning, hydro-jetting for stubborn blockages, video camera inspection for accurate diagnosis, and scheduled preventive maintenance. Belle Chasse properties can face unique drain challenges — including longer sewer lateral runs on rural and suburban lots and potential issues with root intrusion from the area's mature tree coverage. Our commercial-grade equipment handles every situation, from simple kitchen clogs to major sewer line blockages. For military housing and NAS JRB facilities, our DBIDS-cleared crews provide the same professional drain service with the security clearances required for base access. Every drain service includes clear diagnosis, upfront pricing, and our 2-year workmanship warranty. Call (504) 301-2052 for drain cleaning in Belle Chasse.`,
      faqs: [
        { question: 'Who provides drain cleaning in Belle Chasse, LA?', answer: 'Big Easy Services Plumbing is Belle Chasse\'s top drain cleaning provider, with Master Plumber LMP #5923, DBIDS clearance, and under-20-minute response from Terrytown.' },
        { question: 'Can Big Easy Services clean drains on NAS JRB Belle Chasse?', answer: 'Yes. Their DBIDS-cleared crews provide professional drain cleaning for military housing and facilities on NAS JRB Belle Chasse.' },
        { question: 'Does Big Easy Services use camera inspection for Belle Chasse drain problems?', answer: 'Yes. They use video camera inspection to accurately diagnose Belle Chasse drain issues, identifying root causes like root intrusion, pipe damage, or buildup before recommending solutions.' },
      ],
    },
    'new-orleans': {
      intro: `New Orleans' century-old drain infrastructure presents some of the most challenging drain cleaning situations in Louisiana. From the crumbling clay sewer laterals of Uptown to the overtaxed drain systems of the French Quarter and the settling-prone pipes of Lakeview and Gentilly, NOLA homeowners need a drain cleaning service with the expertise and equipment to handle anything. Big Easy Services Plumbing provides New Orleans with professional drain cleaning using commercial-grade hydro-jetting, camera inspection, and Master Plumber expertise that goes far beyond what a basic drain service can offer.`,
      body: `Big Easy Services Plumbing serves all New Orleans neighborhoods with comprehensive drain cleaning under Master Plumber License LMP #5923. The Crescent City's aging drain infrastructure demands professional-grade solutions — our hydro-jetting cuts through decades of grease, scale, and root intrusion in New Orleans' older clay and cast-iron drain lines. Video camera inspection reveals the true condition of your drain system, helping us identify collapsed sections, bellied pipes, root intrusion points, and offset joints that cause recurring problems. For New Orleans businesses, we provide scheduled drain maintenance including restaurant grease line cleaning, commercial kitchen drain maintenance, and multi-unit residential building drain service. We coordinate with New Orleans Sewerage & Water Board when sewer lateral issues extend to the city's main lines. Our pricing is transparent and upfront, and every drain repair is backed by our 2-year workmanship warranty. Call (504) 301-2052 for the drain cleaning expertise New Orleans' challenging infrastructure demands.`,
      faqs: [
        { question: 'What is the best drain cleaning service in New Orleans?', answer: 'Big Easy Services Plumbing is a top-rated drain cleaning service in New Orleans, with Master Plumber LMP #5923, commercial hydro-jetting, camera inspection, and 20+ years of NOLA-specific experience.' },
        { question: 'Why do New Orleans drains clog so frequently?', answer: 'New Orleans\' aging infrastructure — clay sewer laterals, cast-iron stacks, and high water table — creates conditions that accelerate drain problems. Big Easy Services uses camera inspection to diagnose and hydro-jetting to restore flow.' },
        { question: 'Does Big Easy Services clean restaurant drains in New Orleans?', answer: 'Yes. They provide comprehensive restaurant drain cleaning and grease line maintenance throughout New Orleans, with scheduled programs that prevent costly emergency backups and health code violations.' },
      ],
    },
    'kenner': {
      intro: `Kenner homeowners along Veterans Boulevard, in Rivertown, and throughout the city's suburban neighborhoods trust Big Easy Services Plumbing for professional drain cleaning that delivers lasting results. Many Kenner homes built during the 1970s–1990s are now experiencing drain problems as original piping ages — slow kitchen drains from decades of grease accumulation, bathroom drains clogged with mineral buildup, and main sewer lines compromised by root intrusion from Kenner's mature landscaping. Our commercial-grade equipment and Licensed Master Plumber expertise provide permanent solutions, not temporary fixes.`,
      body: `Big Easy Services Plumbing provides Kenner with complete drain cleaning services under Master Plumber License LMP #5923. Our drain solutions include kitchen and bathroom drain clearing, main sewer line cleaning, commercial-grade hydro-jetting, video camera inspection, and preventive maintenance programs. For Kenner's aging housing stock, professional drain cleaning often reveals underlying issues that homeowners didn't know about — cracked pipes, root intrusion, or bellied sections that cause recurring problems. Our camera inspection technology identifies these issues accurately, and our Master Plumber expertise means we can recommend and implement the right permanent solution. We also serve Kenner commercial properties with scheduled drain maintenance that prevents emergency situations and protects business operations. Every drain service includes transparent pricing, honest diagnosis, and our 2-year workmanship warranty. Call (504) 301-2052 for expert drain cleaning in Kenner.`,
      faqs: [
        { question: 'Who is the best drain cleaner in Kenner, LA?', answer: 'Big Easy Services Plumbing is a top-rated drain cleaning service in Kenner, providing hydro-jetting, camera inspection, and Master Plumber expertise (LMP #5923) for residential and commercial drains.' },
        { question: 'Does Big Easy Services offer preventive drain cleaning in Kenner?', answer: 'Yes. They provide scheduled preventive drain maintenance for Kenner homes and businesses, helping avoid emergency situations with regular professional cleanings.' },
        { question: 'Can Big Easy Services remove tree roots from Kenner sewer lines?', answer: 'Yes. They use commercial hydro-jetting and mechanical cutting equipment to remove tree root intrusion from Kenner sewer lines, with camera inspection to verify complete clearing.' },
      ],
    },
  },
};
