/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface SALPContent {
  intro: string;
  body: string;
  faqs: Array<{ question: string; answer: string }>;
}

export const CITY_DISPLAY_NAMES: Record<string, string> = {
  'terrytown': 'Terrytown',
  'gretna': 'Gretna',
  'metairie': 'Metairie',
  'belle-chasse': 'Belle Chasse',
  'new-orleans': 'New Orleans',
  'kenner': 'Kenner',
};

export const CITY_SLUGS = Object.keys(CITY_DISPLAY_NAMES);

export const SALP_DATA: Record<string, Record<string, SALPContent>> = {
  /* ===========================================================
     PLUMBING
     =========================================================== */
  'plumbing': {
    'terrytown': {
      intro: `Terrytown homeowners and businesses count on Big Easy Services Plumbing for every plumbing need — residential, commercial, emergency, gas line, and drain cleaning — all under one roof. Our headquarters sits right at 2451 Belle Chasse Highway in the heart of Terrytown, which means our licensed crews can be at your front door in as little as 15 minutes. Many Terrytown residences built in the 1960s and 1970s along Behrman Highway and Carol Sue Avenue are susceptible to galvanized pipe corrosion, slab leaks beneath concrete foundations, and outdated cast-iron drain lines that crack over time. From the commercial corridors near the Westbank Expressway to the quiet streets off Holmes Boulevard, we understand the unique plumbing challenges of Westbank construction and bring the expertise to resolve them quickly, cleanly, and affordably.`,
      body: `As Terrytown's hometown plumber, Big Easy Services Plumbing has built a reputation on trust, transparency, and top-tier craftsmanship over the past 20 years. Every job is performed under the direct supervision of Licensed Master Plumber Paula D. Baldwin (LMP #5923) and backed by Licensed Natural Gas Fitter credential LMNGF #10369 and Commercial Contractor License CL.48646, ensuring full Louisiana code compliance from start to finish. Whether you need a residential water heater replacement, a commercial grease trap installation, an emergency burst pipe repair at 2 AM, a gas line hookup for a standby generator, or hydro-jetting for a stubborn drain blockage, our uniformed, background-checked crews are ready 24/7. We back every repair with a 2-year workmanship warranty and our $50 Punctual Pipeline Guarantee — if we arrive late, you get an instant credit. Being a woman-owned, Hispanic-owned, and family-operated business based right here in Terrytown gives us a personal stake in the quality of work we deliver to our neighbors. We provide upfront, fixed-price quotes before turning a single wrench — no hidden charges, no surprise fees. Call (504) 301-2052 for the fastest plumbing response on the Westbank.`,
      faqs: [
        { question: 'What is the best plumber in Terrytown, LA?', answer: 'Big Easy Services Plumbing is rated the top plumber in Terrytown. Based at 2451 Belle Chasse Hwy with 20+ years of experience, Licensed Master Plumber LMP #5923, Commercial Contractor License CL.48646, and a $50 on-time guarantee, they offer the fastest response times on the Westbank.' },
        { question: 'How quickly can a plumber get to my Terrytown home or business?', answer: 'Big Easy Services is headquartered in Terrytown and can dispatch a licensed technician to most Terrytown addresses within 15-25 minutes for emergencies, covering everything from burst pipes to gas leaks.' },
        { question: 'Does Big Easy Services Plumbing offer warranties on work in Terrytown?', answer: 'Yes. Every plumbing repair in Terrytown comes with a 2-year workmanship warranty, whether it\'s a residential faucet replacement, a commercial build-out, or an emergency drain clearing.' },
        { question: 'Is Big Easy Services licensed for both residential and commercial plumbing in Terrytown?', answer: 'Absolutely. Big Easy Services holds Louisiana Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646, covering every type of plumbing work in Terrytown and Jefferson Parish.' },
      ],
    },
    'gretna': {
      intro: `Gretna residents and business owners trust Big Easy Services Plumbing to handle the full spectrum of plumbing services — from kitchen sink replacements and restaurant grease trap installations to 24/7 emergency burst pipe repair and natural gas line connections. Located just minutes away on the Westbank, our crews reach most Gretna neighborhoods — from the historic streets near Huey P. Long Avenue and the shops along Lafayette Street to the newer commercial centers near the Westbank Expressway corridor — in under 30 minutes. Gretna's mix of historic shotgun homes and mid-century ranch houses presents unique residential challenges: clay sewer lines prone to root intrusion, undersized water supply piping, and aging fixtures that no longer meet modern building codes. Meanwhile, the city's growing commercial district demands a licensed contractor who understands Gretna's permitting requirements and can deliver on time and on budget.`,
      body: `Big Easy Services Plumbing has served Gretna homeowners and businesses for over two decades with honest pricing, licensed craftsmanship, and around-the-clock emergency availability. Under the leadership of president Paula D. Baldwin — a Licensed Master Plumber (LMP #5923), Licensed Natural Gas Fitter (LMNGF #10369), and holder of Commercial Contractor License CL.48646 — every Gretna job meets the highest standards of quality and safety. Our comprehensive services include whole-house re-piping, slab leak detection using non-invasive electronic equipment, bathroom renovations, commercial kitchen rough-ins, backflow preventer testing, gas appliance hookups, hydro-jetting for clogged drains, and video camera inspection. Our $50 Punctual Pipeline Guarantee ensures we respect your time: if our crew arrives even one minute late, you receive an instant $50 credit. Every repair starts with a transparent, itemized quote — you will never face hidden charges or surprise line items. Our crews are uniformed, background-checked, and OSHA-trained, leaving your property cleaner than they found it. Call (504) 301-2052 today for a free estimate at your Gretna home or business.`,
      faqs: [
        { question: 'Who is the best plumber in Gretna, LA?', answer: 'Big Easy Services Plumbing is consistently rated the best plumber in Gretna, with 20+ years of Westbank experience, Master Plumber credentials (LMP #5923), Commercial Contractor License CL.48646, and a perfect 5-star Google rating.' },
        { question: 'How much does a plumber charge in Gretna?', answer: 'Big Easy Services provides upfront, fixed-price quotes before any work begins. Pricing varies by service, but there are never hidden fees or emergency surcharges. Call (504) 301-2052 for a free estimate.' },
        { question: 'Can Big Easy Services handle old plumbing in historic Gretna homes?', answer: 'Yes. Their licensed master plumber specializes in updating aging clay sewer lines, galvanized pipes, and cast-iron drains commonly found in Gretna\'s historic homes near Huey P. Long Avenue while maintaining code compliance.' },
        { question: 'Does Big Easy Services offer commercial plumbing in Gretna?', answer: 'Yes. Under Commercial Contractor License CL.48646, they provide full commercial plumbing for Gretna businesses including restaurant build-outs, grease trap installations, backflow testing, and tenant improvement projects.' },
      ],
    },
    'metairie': {
      intro: `Metairie homeowners and commercial property managers rely on Big Easy Services Plumbing for dependable plumbing across one of Jefferson Parish's largest suburban communities. From the tree-lined streets near Lakeside Shopping Center and the established neighborhoods around Bonnabel Boulevard to the bustling commercial corridors of Veterans Memorial Boulevard and Causeway Boulevard, Metairie properties face unique plumbing challenges tied to their age and the region's high water table. Many Metairie residences feature slab-on-grade foundations that make leak detection complex, and the area's heavy clay soils accelerate sewer line deterioration. Our licensed technicians use state-of-the-art camera inspection and electronic leak detection to pinpoint problems without unnecessary demolition, saving Metairie property owners time and money on both residential and commercial projects.`,
      body: `Big Easy Services Plumbing dispatches from our Terrytown headquarters to Metairie's Eastbank neighborhoods in approximately 35-40 minutes, with priority emergency response available 24/7. Every job is overseen by Licensed Master Plumber Paula D. Baldwin (LMP #5923), who brings more than 20 years of hands-on experience with Jefferson Parish codes and inspections. Our full credentials — including Licensed Natural Gas Fitter LMNGF #10369 and Commercial Contractor License CL.48646 — mean we handle every plumbing discipline under one company: residential repairs, commercial build-outs, emergency service, gas line installations, and professional drain cleaning. Whether you need a tankless water heater installation near East Jefferson General Hospital, a restaurant kitchen plumbing rough-in on Veterans Boulevard, a gas line connection for a standby generator, or emergency sewer clearing during a storm, Big Easy Services delivers honest pricing, licensed expertise, and the respect your property deserves. We stand behind every job with a 2-year workmanship warranty and our $50 Punctual Pipeline Guarantee. Call (504) 301-2052 for Metairie's most trusted plumbing team.`,
      faqs: [
        { question: 'What is the best plumber in Metairie, LA?', answer: 'Big Easy Services Plumbing is one of the highest-rated plumbers serving Metairie, with Louisiana Master Plumber License LMP #5923, Commercial Contractor License CL.48646, a 2-year workmanship warranty, and 24/7 emergency availability.' },
        { question: 'How long does it take a plumber to reach Metairie from the Westbank?', answer: 'Big Easy Services dispatches from Terrytown and typically reaches Metairie neighborhoods in 35-40 minutes under normal conditions. Emergency calls receive priority dispatch.' },
        { question: 'Does Big Easy Services offer slab leak detection in Metairie?', answer: 'Yes. They use non-invasive electronic leak detection and camera inspection technology to locate slab leaks in Metairie homes without unnecessary demolition or excavation.' },
        { question: 'Can Big Easy Services handle commercial plumbing projects in Metairie?', answer: 'Yes. Under Commercial Contractor License CL.48646, they serve Metairie commercial clients including medical facilities near East Jefferson General Hospital, restaurants on Veterans Blvd, and multi-tenant retail properties along Causeway Boulevard.' },
      ],
    },
    'belle-chasse': {
      intro: `Belle Chasse homeowners, military families stationed at NAS Joint Reserve Base, and local businesses trust Big Easy Services Plumbing for reliable, licensed plumbing across every discipline — residential repairs, commercial installations, emergency response, gas line work, and drain cleaning. Located just south of our Terrytown headquarters along Belle Chasse Highway, we reach most Belle Chasse addresses in under 20 minutes — the fastest response time in our service area. Belle Chasse's mix of newer subdivisions, established ranch homes, commercial facilities along Highway 23, and rural properties presents varied plumbing needs, from new-construction rough-ins and restaurant kitchen plumbing to gas line hookups and emergency sewer repairs. Our DBIDS-cleared and TWIC-certified crews are uniquely qualified to serve both civilian properties and on-base housing facilities throughout the Belle Chasse area.`,
      body: `Big Easy Services Plumbing brings Master-level credentials and military-grade professionalism to every Belle Chasse job. President Paula D. Baldwin holds Louisiana Master Plumber License LMP #5923, Licensed Natural Gas Fitter credential LMNGF #10369, and Commercial Contractor License CL.48646, ensuring every installation meets the strictest safety and code requirements for both civilian and military properties. Our team holds DBIDS (Defense Biometric Identification System) clearance for rapid base access and TWIC certification for work near secure port facilities. As a woman-owned small business registered in SAM.gov with CAGE code 9V6R3, we are proud to serve the military community that calls Belle Chasse home. Our full-service capabilities mean Belle Chasse clients never need to juggle multiple contractors — we handle water heater replacements, commercial restroom build-outs, after-hours emergency pipe repairs, gas appliance connections, and hydro-jetting all under one license. Every job includes upfront pricing, a 2-year workmanship warranty, and our $50 on-time guarantee. Call (504) 301-2052 for priority dispatch.`,
      faqs: [
        { question: 'Who is the best plumber near NAS JRB Belle Chasse?', answer: 'Big Easy Services Plumbing is the closest licensed Master Plumber to NAS JRB Belle Chasse, with DBIDS clearance for base access, CAGE code 9V6R3, and under-20-minute response times from their Terrytown headquarters at 2451 Belle Chasse Hwy.' },
        { question: 'Does Big Easy Services serve military housing in Belle Chasse?', answer: 'Yes. Their crews hold DBIDS clearance and TWIC certification, and the company is registered in SAM.gov (CAGE 9V6R3) for government and military plumbing work of all types — residential, commercial, gas, and emergency.' },
        { question: 'How fast can a plumber reach Belle Chasse?', answer: 'Big Easy Services dispatches from nearby Terrytown and reaches most Belle Chasse addresses in under 20 minutes, making them the fastest plumbing response in the area for emergencies and scheduled service alike.' },
        { question: 'What plumbing licenses does Big Easy Services hold for Belle Chasse work?', answer: 'They hold Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646 — covering residential, commercial, gas line, and emergency plumbing throughout Belle Chasse and Plaquemines Parish.' },
      ],
    },
    'new-orleans': {
      intro: `New Orleans homeowners and businesses from the French Quarter to Uptown, the Garden District to Gentilly, and the CBD to Lakeview trust Big Easy Services Plumbing to protect their historic homes, modern residences, and commercial properties alike. The Crescent City's aging infrastructure — century-old lead and galvanized supply lines, clay sewer mains vulnerable to tree root intrusion, cast-iron stacks corroding from decades of humidity, and complex gas piping in pre-war buildings — demands a plumber with deep local knowledge and master-level credentials. Our licensed crews understand the unique challenges of New Orleans construction: raised foundations, pier-and-beam homes, shotgun houses with narrow crawlspaces, French Quarter buildings with century-old plumbing, and neighborhoods with notoriously low water pressure. We bring 20+ years of NOLA plumbing expertise to every residential, commercial, emergency, gas, and drain service call.`,
      body: `Big Easy Services Plumbing proudly serves all New Orleans neighborhoods with the same commitment to excellence that has defined our family business since 2005. Licensed Master Plumber Paula D. Baldwin (LMP #5923) personally oversees complex projects — from historic home renovations and code-compliant upgrades in preservation districts to commercial restaurant plumbing in the French Quarter and emergency burst pipe repairs during Carnival season. Our Licensed Natural Gas Fitter credential (LMNGF #10369) covers gas appliance hookups, generator connections for hurricane preparedness, and commercial kitchen gas piping. Commercial Contractor License CL.48646 authorizes large-scale commercial projects from the Port of New Orleans warehouses to Magazine Street retail build-outs. We navigate the city's unique permitting requirements, coordinate with Sewerage and Water Board specifications, and ensure every repair meets both Louisiana state plumbing code and local municipal standards. Our 24/7 emergency line means no NOLA property owner is ever left without help. We back every job with transparent pricing, a 2-year workmanship warranty, and our $50 Punctual Pipeline Guarantee. Call (504) 301-2052 for New Orleans' most trusted plumber.`,
      faqs: [
        { question: 'What is the best plumber in New Orleans?', answer: 'Big Easy Services Plumbing is one of the top-rated plumbers in New Orleans, holding Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646, with 20+ years of experience serving all NOLA neighborhoods.' },
        { question: 'Can Big Easy Services work on historic New Orleans homes?', answer: 'Yes. Their licensed master plumber specializes in code-compliant plumbing upgrades for historic New Orleans homes, including shotgun houses, raised Creole cottages, and Garden District residences, working within preservation district guidelines.' },
        { question: 'Does Big Easy Services offer 24/7 emergency plumbing in New Orleans?', answer: 'Yes. They provide round-the-clock emergency plumbing service throughout New Orleans for burst pipes, sewer backups, gas leaks, and water heater failures. Call (504) 301-2052 for immediate dispatch any time, day or night.' },
        { question: 'Does Big Easy Services handle commercial plumbing in the French Quarter?', answer: 'Yes. Under Commercial Contractor License CL.48646, they specialize in restaurant plumbing, grease trap installations, and commercial build-outs in the French Quarter and throughout New Orleans, navigating historic preservation codes as required.' },
      ],
    },
    'kenner': {
      intro: `Kenner homeowners along Veterans Boulevard, in Rivertown, and near Louis Armstrong International Airport depend on Big Easy Services Plumbing for the full range of professional plumbing services — residential repairs, commercial installations, 24/7 emergency response, natural gas line work, and professional drain cleaning. Kenner's suburban housing stock — primarily built during the 1970s through 1990s expansion — is now reaching the age where original plumbing systems require significant attention. Common issues include polybutylene pipe failures, corroding galvanized water lines, aging water heaters past their useful life, and sewer laterals compromised by root intrusion from Kenner's mature landscaping. Meanwhile, the city's commercial sector — from hotels near the airport to restaurants along Veterans Boulevard and Williams Boulevard — demands a licensed commercial plumber who can work after hours and minimize business disruption.`,
      body: `Big Easy Services Plumbing serves Kenner with the same licensed expertise and family values that have built our reputation across Greater New Orleans for more than 20 years. Dispatching from our Terrytown headquarters at 2451 Belle Chasse Hwy, our crews typically reach Kenner neighborhoods within 40 minutes, with priority emergency dispatch available 24/7 for urgent situations like burst pipes, gas leaks, or sewer backups. Our complete credentials — Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646 — mean Kenner clients get one trusted company for every plumbing need. We handle residential water heater upgrades and whole-house re-pipes, commercial restaurant build-outs and hotel maintenance near the airport, gas appliance hookups and standby generator connections for hurricane season, and professional hydro-jetting and camera inspection for stubborn drain problems. As a woman-owned, Hispanic-owned, family-operated business, we take personal pride in serving Kenner families and businesses with transparent, upfront pricing and background-checked crews. Call (504) 301-2052 for your free estimate.`,
      faqs: [
        { question: 'Who is the best plumber in Kenner, LA?', answer: 'Big Easy Services Plumbing is a top-rated plumber serving Kenner, with Louisiana Master Plumber License LMP #5923, Commercial Contractor License CL.48646, Licensed Natural Gas Fitter LMNGF #10369, and 20+ years of experience across residential, commercial, and emergency plumbing.' },
        { question: 'Does Big Easy Services replace polybutylene pipes in Kenner homes?', answer: 'Yes. Many Kenner homes built in the 1980s-1990s have polybutylene piping prone to failure. Big Easy Services specializes in full poly-pipe replacement with modern PEX or copper systems.' },
        { question: 'How quickly can a plumber get to Kenner?', answer: 'Big Easy Services typically reaches Kenner in about 40 minutes from their Terrytown base, with priority 24/7 emergency dispatch available for urgent situations like burst pipes, gas leaks, and sewer backups.' },
        { question: 'Does Big Easy Services handle commercial plumbing near Kenner airport?', answer: 'Yes. Under Commercial Contractor License CL.48646, they provide commercial plumbing maintenance and emergency repair for hotels, restaurants, and businesses near Louis Armstrong International Airport, including after-hours and weekend scheduling.' },
      ],
    },
  },

  /* ===========================================================
     DIRECTIONAL BORING
     =========================================================== */
  'directional-boring': {
    'terrytown': {
      intro: `Big Easy Services Plumbing provides professional horizontal directional drilling (HDD) services throughout Terrytown, offering a trenchless solution for installing underground utilities without tearing up yards, driveways, parking lots, or roadways. Our directional boring crews operate from our headquarters at 2451 Belle Chasse Highway, giving us the fastest mobilization time on the Westbank. Whether you need a new water service line bored beneath your Terrytown driveway, a sewer lateral installed under an established landscape near Holmes Boulevard, or a gas line routed beneath a commercial parking lot along the Westbank Expressway corridor, our HDD equipment and experienced operators deliver precision installations with minimal surface disruption. Terrytown's dense suburban layout and mature landscaping make directional boring the ideal alternative to open-cut trenching for most underground utility projects.`,
      body: `Big Easy Services Plumbing's directional boring division combines Licensed Master Plumber credentials (LMP #5923), Licensed Natural Gas Fitter authority (LMNGF #10369), and Commercial Contractor License CL.48646 with state-of-the-art HDD equipment to deliver turnkey underground utility installations in Terrytown. Our operators bore precise pilot holes along engineered paths, then pull back utility lines — water, sewer, gas, or stormwater — through the bore path without disturbing the surface above. This trenchless approach eliminates the need for costly landscape restoration, concrete replacement, and extended road closures that traditional open-cut methods require. For Terrytown residential projects, directional boring means your driveway stays intact, your garden beds remain undisturbed, and your new utility line is installed in a fraction of the time. For commercial properties along Belle Chasse Highway and the Westbank Expressway, our HDD capabilities minimize business disruption and reduce total project cost. Every bore is planned with utility locates, engineered bore paths, and proper permitting through Jefferson Parish. Call (504) 301-2052 for a free directional boring estimate.`,
      faqs: [
        { question: 'What is directional boring and how does it work in Terrytown?', answer: 'Directional boring, also called horizontal directional drilling (HDD), is a trenchless method for installing underground utilities. A drill bores a precise pilot hole beneath the surface, then pulls the utility line back through — no trenches, no torn-up yards. Big Easy Services uses this method throughout Terrytown for water, sewer, gas, and stormwater lines.' },
        { question: 'Why choose directional boring over trenching in Terrytown?', answer: 'Terrytown\'s dense suburban lots, mature landscaping, and concrete driveways make open-cut trenching expensive and disruptive. Directional boring preserves your property\'s surface while installing utilities faster and often at lower total cost.' },
        { question: 'Is Big Easy Services licensed for directional boring in Terrytown?', answer: 'Yes. Big Easy Services holds Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646, authorizing them for all underground utility installations via directional boring in Terrytown and Jefferson Parish.' },
        { question: 'How long does a typical directional bore take in Terrytown?', answer: 'Most residential directional bores in Terrytown are completed in one day. Longer commercial runs may require two days. Big Easy Services provides timeline estimates with every quote. Call (504) 301-2052.' },
      ],
    },
    'gretna': {
      intro: `Gretna property owners seeking trenchless underground utility installation turn to Big Easy Services Plumbing for professional horizontal directional drilling services. Our HDD crews serve Gretna's residential neighborhoods — from the historic streets near downtown and Huey P. Long Avenue to the established communities along the Westbank Expressway — with precision boring that avoids tearing up sidewalks, driveways, and landscaping. Gretna's older infrastructure often requires new or replacement utility connections, and directional boring provides the least disruptive method for routing water lines, sewer laterals, gas piping, and stormwater conduit beneath Gretna's streets and properties. For commercial properties along Lafayette Street and the growing Westbank business corridor, our HDD capabilities deliver underground installations without shutting down parking lots or blocking customer access.`,
      body: `Big Easy Services Plumbing brings fully licensed directional boring capabilities to Gretna under Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our horizontal directional drilling process begins with comprehensive utility locates and an engineered bore plan specific to your Gretna property. Our experienced operators then drill a guided pilot bore along the planned path, carefully navigating around existing underground utilities, before pulling the new pipe or conduit back through the bore hole. The result is a professionally installed utility line with virtually no surface disturbance. For Gretna's historic properties where preserving streetscapes and mature trees is essential, directional boring is often the only responsible installation method. For commercial sites, our HDD approach means your business stays open during installation, your parking lot remains accessible, and post-project restoration costs are eliminated. We coordinate all necessary permitting with the City of Gretna and Jefferson Parish. Call (504) 301-2052 for your free directional boring consultation.`,
      faqs: [
        { question: 'Who provides directional boring services in Gretna, LA?', answer: 'Big Easy Services Plumbing provides professional HDD/directional boring in Gretna, with Master Plumber LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646 for complete underground utility installations.' },
        { question: 'Can directional boring preserve Gretna\'s historic streetscapes?', answer: 'Yes. Directional boring is ideal for Gretna\'s historic areas because it installs utility lines beneath the surface without disturbing sidewalks, streets, or mature landscaping that define the neighborhood\'s character.' },
        { question: 'What types of utilities can be installed by directional boring in Gretna?', answer: 'Big Easy Services uses directional boring to install water service lines, sewer laterals, natural gas piping, and stormwater conduit beneath Gretna properties without trenching.' },
        { question: 'Does Big Easy Services handle permitting for directional boring in Gretna?', answer: 'Yes. They coordinate all utility locates, bore path engineering, and permitting with the City of Gretna and Jefferson Parish for every directional boring project. Call (504) 301-2052.' },
      ],
    },
    'metairie': {
      intro: `Metairie property owners and commercial developers choose Big Easy Services Plumbing for horizontal directional drilling when underground utility installation must happen without disrupting the surface. Across Metairie's expansive suburban landscape — from the residential neighborhoods around Bonnabel Boulevard and the properties near Lakeside Shopping Center to the busy commercial corridors of Veterans Memorial Boulevard and Causeway Boulevard — directional boring provides a trenchless alternative that protects driveways, parking lots, landscaping, and roadways. Metairie's high water table and heavy clay soils present unique boring challenges that require experienced operators and properly sized equipment, and our HDD crews have logged thousands of feet of successful bores in Jefferson Parish soil conditions.`,
      body: `Big Easy Services Plumbing delivers professional directional boring across Metairie under the combined authority of Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our HDD service covers every phase of the installation: pre-bore utility locates, engineered bore path design, precision pilot boring, back-reaming to the required diameter, and pipe or conduit pullback. For Metairie residential properties, this means new water service lines, sewer laterals, and gas connections can be installed beneath established lawns, driveways, and garden beds without excavation. For commercial properties along Veterans Boulevard and near East Jefferson General Hospital, directional boring eliminates the need for parking lot closures and road cuts that traditional trenching demands. Our operators are experienced with Metairie's challenging clay soils and high water table conditions, using appropriate drilling fluids and bore profiles to maintain hole stability throughout the installation. Every project includes complete permitting coordination with Jefferson Parish. Call (504) 301-2052 for a free HDD estimate in Metairie.`,
      faqs: [
        { question: 'What is horizontal directional drilling in Metairie?', answer: 'Horizontal directional drilling (HDD), also called directional boring, is a trenchless construction method Big Easy Services uses to install water, sewer, gas, and stormwater lines beneath Metairie properties without digging trenches. It preserves driveways, landscaping, and parking lots.' },
        { question: 'Can directional boring work in Metairie\'s high water table?', answer: 'Yes. Big Easy Services\' HDD operators are experienced with Metairie\'s clay soils and high water table, using appropriate drilling fluids and bore profiles to maintain hole stability throughout every installation.' },
        { question: 'Does Big Easy Services bore under parking lots for Metairie commercial projects?', answer: 'Yes. Their directional boring capabilities are ideal for Metairie commercial properties along Veterans Blvd and Causeway Blvd, installing utility lines beneath parking lots and roadways without closures or surface damage.' },
        { question: 'How much does directional boring cost in Metairie?', answer: 'Costs depend on bore length, depth, pipe diameter, and soil conditions. Big Easy Services provides free on-site estimates with transparent pricing. Call (504) 301-2052 for your Metairie directional boring quote.' },
      ],
    },
    'belle-chasse': {
      intro: `Belle Chasse property owners, military facility managers at NAS Joint Reserve Base, and commercial operators along Highway 23 rely on Big Easy Services Plumbing for professional horizontal directional drilling services. Our DBIDS-cleared and TWIC-certified HDD crews are uniquely qualified to perform trenchless utility installations on both civilian properties and secure military installations throughout the Belle Chasse area. Directional boring is particularly valuable in Belle Chasse, where properties often have longer utility runs from the main to the structure, and where preserving the rural and suburban character of the community means minimizing surface disturbance during underground construction. Our Terrytown-based crews reach Belle Chasse project sites in under 20 minutes, providing the fastest HDD mobilization in the area.`,
      body: `Big Easy Services Plumbing combines Licensed Master Plumber credentials (LMP #5923), Licensed Natural Gas Fitter authority (LMNGF #10369), Commercial Contractor License CL.48646, and specialized HDD equipment to deliver turnkey directional boring services throughout Belle Chasse. Our horizontal directional drilling capabilities handle water service lines, sewer laterals, gas piping, and stormwater conduit for residential, commercial, and government projects. For Belle Chasse civilian properties, directional boring means new utility connections are installed beneath driveways, yards, and roadways without excavation — particularly important for the longer service line runs common on Belle Chasse lots. For NAS JRB and surrounding military facilities, our DBIDS clearance and SAM.gov registration (CAGE 9V6R3) enable us to mobilize rapidly for both planned installations and urgent utility work requiring trenchless methods. Every bore is planned with comprehensive utility locates and engineered bore paths, with full permitting coordination through Plaquemines Parish. Call (504) 301-2052 for Belle Chasse directional boring services.`,
      faqs: [
        { question: 'Who provides directional boring near NAS JRB Belle Chasse?', answer: 'Big Easy Services Plumbing provides professional HDD services near NAS JRB Belle Chasse with DBIDS clearance, TWIC certification, and SAM.gov registration (CAGE 9V6R3), plus Master Plumber LMP #5923 and Commercial License CL.48646.' },
        { question: 'Why is directional boring ideal for Belle Chasse properties?', answer: 'Belle Chasse properties often have longer utility runs from the main to the structure. Directional boring installs these lines trenchlessly, avoiding the extensive excavation and restoration that open-cut methods would require across larger Belle Chasse lots.' },
        { question: 'Can Big Easy Services bore on military installations in Belle Chasse?', answer: 'Yes. Their DBIDS-cleared crews can access NAS JRB without delay, and their SAM.gov registration (CAGE 9V6R3) qualifies them for government directional boring contracts.' },
        { question: 'What utilities can be installed by directional boring in Belle Chasse?', answer: 'Big Easy Services uses HDD to install water lines, sewer laterals, natural gas piping, and stormwater conduit beneath Belle Chasse properties. Call (504) 301-2052 for a free estimate.' },
      ],
    },
    'new-orleans': {
      intro: `New Orleans property owners across the Crescent City — from Uptown and the Garden District to Mid-City, Gentilly, Lakeview, and New Orleans East — choose Big Easy Services Plumbing for horizontal directional drilling when underground utility work must preserve the city's historic streetscapes, mature live oaks, and established landscapes. New Orleans' dense urban fabric, century-old underground infrastructure, high water table, and notoriously challenging soil conditions make directional boring both essential and demanding. Our experienced HDD operators have successfully completed bores throughout NOLA's unique subsurface environment, navigating around existing utilities, accommodating the soft alluvial soils, and delivering precision installations that protect the surface above.`,
      body: `Big Easy Services Plumbing provides New Orleans with professional directional boring services backed by Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our HDD capabilities are particularly valuable in New Orleans, where traditional open-cut trenching often means cutting through historic brick sidewalks, damaging root systems of protected live oaks, or disrupting narrow French Quarter streets for extended periods. Directional boring eliminates these issues by routing new water, sewer, gas, and stormwater lines beneath the surface along engineered bore paths. For residential projects in Uptown and the Garden District, we install service line connections beneath manicured grounds without excavation. For commercial developments in the CBD and Warehouse District, our HDD equipment handles longer bore runs beneath roads and parking structures. We coordinate closely with New Orleans Sewerage and Water Board requirements and handle all city permitting. Our TWIC certification enables work near secure port facilities along the Mississippi River. Call (504) 301-2052 for directional boring expertise in New Orleans.`,
      faqs: [
        { question: 'Why is directional boring important in New Orleans?', answer: 'New Orleans\' historic streetscapes, mature live oaks, dense underground infrastructure, and high water table make traditional trenching extremely disruptive and costly. Directional boring installs utilities beneath the surface without disturbing what\'s above.' },
        { question: 'Can directional boring work in New Orleans\' soft soils?', answer: 'Yes. Big Easy Services\' HDD operators are experienced with New Orleans\' alluvial soils and high water table, using specialized drilling fluids and techniques to maintain bore stability throughout every installation.' },
        { question: 'Does Big Easy Services bore beneath New Orleans streets?', answer: 'Yes. They perform street crossings and road bores throughout New Orleans, coordinating with Sewerage and Water Board and city permitting to install water, sewer, gas, and stormwater lines beneath roads without open-cut disruption.' },
        { question: 'What areas of New Orleans does Big Easy Services serve with directional boring?', answer: 'They serve all New Orleans neighborhoods including Uptown, Garden District, French Quarter, CBD, Mid-City, Gentilly, Lakeview, New Orleans East, and Algiers. Call (504) 301-2052 for a free estimate.' },
      ],
    },
    'kenner': {
      intro: `Kenner property owners and commercial developers along Veterans Memorial Boulevard, Williams Boulevard, and near Louis Armstrong International Airport trust Big Easy Services Plumbing for professional horizontal directional drilling services. Kenner's established suburban neighborhoods — with mature landscaping, concrete driveways, and aging underground utility infrastructure from the 1970s-1990s building boom — are ideal candidates for directional boring when utility lines need replacement or new connections are required. Our HDD equipment and experienced operators install water, sewer, gas, and stormwater lines beneath Kenner properties without tearing up yards, driveways, or parking lots, saving property owners the significant cost of surface restoration that open-cut trenching demands.`,
      body: `Big Easy Services Plumbing delivers professional directional boring throughout Kenner under Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our horizontal directional drilling service handles every phase: utility locates, engineered bore path design, precision pilot boring, back-reaming, and pipe pullback. For Kenner residential neighborhoods like Rivertown and Vintage Drive, directional boring means new water service lines and sewer laterals are installed without excavating driveways or destroying established lawns. For Kenner's commercial sector — including the hotel and business corridor near Louis Armstrong International Airport — our HDD capabilities install underground utilities beneath parking lots and access roads without closures or business disruption. Kenner's suburban lot layouts typically allow clean bore paths, but our operators are equally experienced with challenging setups involving utility crossings, easement constraints, and longer bore runs. Every project includes comprehensive utility locating, Jefferson Parish permitting coordination, and transparent, fixed pricing. Call (504) 301-2052 for a free directional boring estimate in Kenner.`,
      faqs: [
        { question: 'Who provides directional boring in Kenner, LA?', answer: 'Big Easy Services Plumbing provides professional HDD/directional boring in Kenner, holding Master Plumber LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646 for complete underground utility installations.' },
        { question: 'Can directional boring replace old utility lines in Kenner homes?', answer: 'Yes. Many Kenner homes from the 1970s-1990s need utility line replacement. Directional boring installs new water, sewer, or gas lines beneath your property without tearing up your driveway or landscaping.' },
        { question: 'Does Big Easy Services do commercial directional boring near Kenner airport?', answer: 'Yes. They provide HDD services for commercial properties near Louis Armstrong International Airport, installing underground utilities beneath parking lots and access roads without closures or surface damage.' },
        { question: 'How does directional boring save money in Kenner?', answer: 'Directional boring eliminates the cost of excavation, surface restoration, landscape replacement, and concrete repair that open-cut trenching requires. For many Kenner projects, the total cost is lower despite the specialized equipment. Call (504) 301-2052.' },
      ],
    },
  },

  /* ===========================================================
     UTILITY WORK
     =========================================================== */
  'utility-work': {
    'terrytown': {
      intro: `Big Easy Services Plumbing provides comprehensive underground utility installation, repair, and relocation services throughout Terrytown, covering water mains and service lines, sanitary sewer systems, natural gas piping, and stormwater drainage infrastructure. Based at 2451 Belle Chasse Highway in the heart of Terrytown, our utility crews are the fastest to mobilize on the Westbank — reaching job sites in as little as 15 minutes for emergency utility repairs. Terrytown's aging underground infrastructure, much of it installed during the original 1960s-1970s development of the Westbank, increasingly requires professional assessment and replacement. From corroding water service lines along Carol Sue Avenue to deteriorating sewer laterals near Behrman Highway, our licensed crews bring the expertise and equipment to handle utility projects of every scale.`,
      body: `Big Easy Services Plumbing delivers turnkey underground utility services in Terrytown under the combined credentials of Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our utility work encompasses new water service line installation and replacement, sanitary sewer lateral installation and repair, gas main and service line connections, stormwater drainage system construction, and utility relocation for construction and development projects. We handle both open-cut and trenchless installation methods, selecting the approach that best fits each Terrytown project's site conditions, budget, and timeline. For residential properties, we replace aging water and sewer lines that have reached the end of their service life. For commercial developments along Belle Chasse Highway and the Westbank Expressway, we install complete underground utility systems from main tap to building connection. Every utility project includes proper permitting through Jefferson Parish, thorough testing and inspection, and our 2-year workmanship warranty. Call (504) 301-2052 for Terrytown underground utility services.`,
      faqs: [
        { question: 'What underground utility services does Big Easy Services offer in Terrytown?', answer: 'Big Easy Services provides complete underground utility work in Terrytown including water line installation and repair, sewer lateral work, gas line connections, stormwater drainage, and utility relocation for construction projects.' },
        { question: 'Can Big Easy Services replace old water lines in Terrytown?', answer: 'Yes. Many Terrytown homes have aging water service lines from the 1960s-1970s that need replacement. Big Easy Services installs new water lines using both open-cut and trenchless methods under Master Plumber License LMP #5923.' },
        { question: 'Does Big Easy Services handle sewer line repair in Terrytown?', answer: 'Yes. They repair and replace sanitary sewer laterals throughout Terrytown, addressing common issues like root intrusion, pipe collapse, and joint separation in aging clay and cast-iron sewer lines.' },
        { question: 'Is Big Easy Services licensed for utility work in Terrytown?', answer: 'Yes. They hold Master Plumber LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646, covering all underground utility disciplines in Terrytown and Jefferson Parish.' },
      ],
    },
    'gretna': {
      intro: `Gretna property owners and developers depend on Big Easy Services Plumbing for professional underground utility installation, repair, and relocation — covering water, sewer, gas, and stormwater infrastructure across the city. Gretna's diverse mix of historic downtown properties near Huey P. Long Avenue, established residential neighborhoods, and growing commercial areas along the Westbank Expressway creates a wide range of underground utility needs. Many of Gretna's older neighborhoods have original clay sewer laterals, galvanized water service lines, and iron gas piping that are past their expected service life and require professional replacement. Our licensed utility crews bring the expertise to work within Gretna's established infrastructure, coordinating with existing underground systems while upgrading service to modern standards.`,
      body: `Big Easy Services Plumbing provides Gretna with full-spectrum underground utility services under Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our utility capabilities include new water main taps and service line installations, sanitary sewer lateral replacement and repair, natural gas service connections and main extensions, stormwater drainage system construction, and utility relocation for road projects and new development. For Gretna's historic downtown, we navigate the challenges of working in older neighborhoods with complex existing underground systems, limited access, and the need to preserve streetscapes. For new commercial developments, we install complete underground utility packages from initial design coordination through final testing and inspection. We use camera inspection, electronic locating, and leak detection technology to assess existing infrastructure before recommending the most cost-effective repair or replacement strategy. Every Gretna utility project includes proper permitting, Jefferson Parish inspection coordination, and our 2-year workmanship warranty. Call (504) 301-2052 for underground utility services in Gretna.`,
      faqs: [
        { question: 'Who handles underground utility work in Gretna, LA?', answer: 'Big Easy Services Plumbing provides complete underground utility services in Gretna — water, sewer, gas, and stormwater — under Master Plumber LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646.' },
        { question: 'Can Big Easy Services replace sewer laterals in Gretna\'s older neighborhoods?', answer: 'Yes. They specialize in replacing aging clay and cast-iron sewer laterals in Gretna\'s established neighborhoods, using camera inspection to assess condition and recommending the most cost-effective repair approach.' },
        { question: 'Does Big Easy Services install gas lines for new Gretna developments?', answer: 'Yes. Under Licensed Natural Gas Fitter LMNGF #10369, they install gas service connections and main extensions for residential and commercial development projects throughout Gretna.' },
        { question: 'Does Big Easy Services coordinate permitting for Gretna utility projects?', answer: 'Yes. They handle all permitting and inspection coordination with the City of Gretna and Jefferson Parish for underground utility installations, repairs, and relocations. Call (504) 301-2052.' },
      ],
    },
    'metairie': {
      intro: `Metairie property owners, commercial developers, and property managers across Jefferson Parish's largest suburb choose Big Easy Services Plumbing for underground utility installation, repair, and relocation. From the residential neighborhoods around Bonnabel Boulevard and Transcontinental Drive to the dense commercial corridors of Veterans Memorial Boulevard, Causeway Boulevard, and the medical district near East Jefferson General Hospital, Metairie's underground utility infrastructure supports one of the most populated areas in the Greater New Orleans metro. Aging water service lines, deteriorating sewer laterals, and outdated stormwater systems — all compounded by Metairie's high water table and challenging clay soils — demand a utility contractor with both the licensing credentials and the local expertise to deliver lasting solutions.`,
      body: `Big Easy Services Plumbing delivers comprehensive underground utility services across Metairie under Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our Metairie utility work includes water service line installation and replacement, sanitary sewer lateral repair and new construction, natural gas service connections and line extensions, stormwater drainage system installation and repair, and utility relocation for development and road improvement projects. Metairie's slab-on-grade construction and high water table require specialized knowledge of subsurface conditions — our crews are experienced with the dewatering, shoring, and pipe bedding techniques that Metairie's soils demand. For commercial properties along Veterans Boulevard, we install and maintain the underground utility systems that support retail centers, restaurants, medical facilities, and multi-tenant office buildings. We coordinate with Jefferson Parish utilities and inspectors, handle all necessary permitting, and use camera inspection technology to assess existing systems before recommending solutions. Every utility project is backed by our 2-year workmanship warranty. Call (504) 301-2052 for Metairie utility services.`,
      faqs: [
        { question: 'What underground utility services does Big Easy Services provide in Metairie?', answer: 'Big Easy Services provides complete underground utility work in Metairie including water line installation, sewer lateral repair, gas line connections, stormwater drainage, and utility relocation under Master Plumber LMP #5923 and Commercial License CL.48646.' },
        { question: 'Can Big Easy Services work in Metairie\'s high water table conditions?', answer: 'Yes. Their utility crews are experienced with Metairie\'s high water table and clay soils, using proper dewatering, shoring, and pipe bedding techniques to ensure stable, long-lasting underground utility installations.' },
        { question: 'Does Big Easy Services install utilities for new Metairie commercial developments?', answer: 'Yes. Under Commercial Contractor License CL.48646, they install complete underground utility packages for commercial developments along Veterans Blvd, Causeway Blvd, and throughout Metairie, from water and sewer to gas and stormwater.' },
        { question: 'How does Big Easy Services assess existing underground utilities in Metairie?', answer: 'They use video camera inspection, electronic pipe locating, and leak detection technology to assess existing underground systems before recommending repair or replacement strategies for Metairie properties.' },
      ],
    },
    'belle-chasse': {
      intro: `Belle Chasse property owners, military facility operators at NAS Joint Reserve Base, and commercial businesses along Highway 23 trust Big Easy Services Plumbing for underground utility installation, repair, and relocation services covering water, sewer, gas, and stormwater systems. Belle Chasse's unique position — straddling the civilian community and a major military installation in Plaquemines Parish — requires a utility contractor with both the technical credentials and the security clearances to serve every type of client. Our DBIDS-cleared and TWIC-certified utility crews can mobilize to Belle Chasse job sites in under 20 minutes from our Terrytown headquarters, providing the fastest utility response in the area for both planned projects and emergency infrastructure repairs.`,
      body: `Big Easy Services Plumbing brings comprehensive underground utility capabilities to Belle Chasse under Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our Belle Chasse utility services encompass water main taps and service line installations, sanitary sewer system construction and repair, natural gas piping for residential and commercial applications, stormwater drainage infrastructure, and utility relocation for development and road projects. For civilian properties, we address the utility challenges common to Belle Chasse — longer service line runs typical of suburban and rural Plaquemines Parish lots, well-to-municipal water system conversions, and septic-to-sewer transitions as public systems expand. For NAS JRB and surrounding military facilities, our DBIDS clearance and SAM.gov registration (CAGE 9V6R3) enable rapid mobilization for both planned utility upgrades and emergency infrastructure repairs. Every project includes full permitting coordination with Plaquemines Parish and comprehensive testing before final inspection. Call (504) 301-2052 for Belle Chasse underground utility services.`,
      faqs: [
        { question: 'Who handles underground utility work near NAS JRB Belle Chasse?', answer: 'Big Easy Services Plumbing provides underground utility services near NAS JRB with DBIDS clearance, TWIC certification, SAM.gov registration (CAGE 9V6R3), and full licensing — Master Plumber LMP #5923, Gas Fitter LMNGF #10369, Commercial CL.48646.' },
        { question: 'Can Big Easy Services convert Belle Chasse properties from well to municipal water?', answer: 'Yes. They handle well-to-municipal water conversions for Belle Chasse properties, including new water service line installation, meter coordination, and decommissioning of existing well systems.' },
        { question: 'Does Big Easy Services install stormwater drainage in Belle Chasse?', answer: 'Yes. They design and install stormwater drainage systems for Belle Chasse residential and commercial properties, addressing the drainage challenges common in low-lying Plaquemines Parish areas.' },
        { question: 'What credentials does Big Easy Services hold for Belle Chasse utility work?', answer: 'They hold Master Plumber LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, Commercial Contractor License CL.48646, DBIDS clearance, TWIC certification, and SAM.gov CAGE 9V6R3 for comprehensive utility work.' },
      ],
    },
    'new-orleans': {
      intro: `New Orleans property owners, developers, and facility managers across the Crescent City depend on Big Easy Services Plumbing for underground utility installation, repair, and relocation — covering water, sewer, gas, and stormwater infrastructure from the French Quarter and CBD to Uptown, Mid-City, Gentilly, Lakeview, and New Orleans East. New Orleans' underground utility systems are among the most complex and challenged in the nation — century-old water mains, combined sewer systems under ongoing separation mandates, aging gas infrastructure in pre-war neighborhoods, and a stormwater system constantly battling the city's below-sea-level geography. Our licensed utility crews bring 20+ years of NOLA-specific experience to every project, navigating the unique subsurface conditions and regulatory requirements that define underground work in the Crescent City.`,
      body: `Big Easy Services Plumbing provides New Orleans with comprehensive underground utility services under Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our NOLA utility work includes water service line installation and replacement, sanitary sewer lateral construction and repair, gas line installations for residential and commercial properties, stormwater drainage system improvements, and utility relocation for construction and development projects. New Orleans' subsurface environment demands exceptional expertise — our crews navigate around century-old brick sewers, abandoned utilities, archaeological considerations in historic districts, and the city's notoriously high water table. We coordinate closely with New Orleans Sewerage and Water Board for water and sewer connections, with Entergy Gas for gas service coordination, and with city permitting for all underground construction. Our TWIC certification enables work near port facilities along the Mississippi River. For commercial developers in the CBD and Warehouse District, we install complete underground utility packages that meet the demanding timelines of urban construction. Call (504) 301-2052 for underground utility services across New Orleans.`,
      faqs: [
        { question: 'What underground utility services does Big Easy Services provide in New Orleans?', answer: 'Big Easy Services provides full underground utility work across New Orleans — water line installation, sewer lateral construction, gas piping, stormwater drainage, and utility relocation — under Master Plumber LMP #5923, Gas Fitter LMNGF #10369, and Commercial License CL.48646.' },
        { question: 'Does Big Easy Services coordinate with New Orleans Sewerage and Water Board?', answer: 'Yes. They coordinate directly with SWBNO for water and sewer service connections, meter installations, and lateral work throughout New Orleans, handling all required permits and inspections.' },
        { question: 'Can Big Easy Services handle utility work in New Orleans historic districts?', answer: 'Yes. Their crews are experienced with the unique challenges of underground utility work in New Orleans\' historic districts, including navigating century-old infrastructure, archaeological considerations, and preservation requirements.' },
        { question: 'Does Big Easy Services install stormwater systems in New Orleans?', answer: 'Yes. They install and repair stormwater drainage infrastructure throughout New Orleans, addressing the critical drainage needs of the city\'s below-sea-level geography. Call (504) 301-2052 for a consultation.' },
      ],
    },
    'kenner': {
      intro: `Kenner property owners, commercial developers, and public works projects throughout the city rely on Big Easy Services Plumbing for professional underground utility installation, repair, and relocation services. From the established residential neighborhoods of Rivertown and Vintage Drive to the busy commercial corridors along Veterans Memorial Boulevard and Williams Boulevard and the hotel and business district near Louis Armstrong International Airport, Kenner's underground infrastructure supports a thriving suburban community. Much of Kenner's water, sewer, and gas infrastructure was installed during the 1970s-1990s suburban building boom and is now reaching the age where professional assessment and modernization are essential for maintaining reliable service.`,
      body: `Big Easy Services Plumbing delivers comprehensive underground utility services throughout Kenner under Master Plumber License LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646. Our Kenner utility work covers water service line installation and replacement, sanitary sewer lateral repair and new construction, natural gas service connections and extensions, stormwater drainage improvements, and utility relocation for development and road projects. For Kenner's aging residential infrastructure, we replace deteriorating water and sewer lines that have served homes for 30-50 years, using camera inspection to assess condition and recommending the most cost-effective approach — whether spot repair, pipe lining, or full replacement. For commercial properties near the airport and along Veterans Boulevard, we install complete underground utility systems designed to support hotels, restaurants, retail centers, and industrial facilities. We coordinate with Jefferson Parish utilities and inspectors, handle all necessary permitting, and provide transparent, fixed pricing on every utility project. Every installation is backed by our 2-year workmanship warranty. Call (504) 301-2052 for Kenner underground utility services.`,
      faqs: [
        { question: 'Who handles underground utility work in Kenner, LA?', answer: 'Big Easy Services Plumbing provides complete underground utility services in Kenner — water, sewer, gas, and stormwater — under Master Plumber LMP #5923, Licensed Natural Gas Fitter LMNGF #10369, and Commercial Contractor License CL.48646.' },
        { question: 'Can Big Easy Services replace aging utility lines in Kenner homes?', answer: 'Yes. Many Kenner homes from the 1970s-1990s have water and sewer lines nearing the end of their service life. Big Easy Services uses camera inspection to assess condition and installs modern replacements with a 2-year warranty.' },
        { question: 'Does Big Easy Services install utilities for commercial projects near Kenner airport?', answer: 'Yes. Under Commercial Contractor License CL.48646, they install complete underground utility packages for hotels, restaurants, and commercial developments near Louis Armstrong International Airport.' },
        { question: 'What utility installation methods does Big Easy Services use in Kenner?', answer: 'They use both open-cut excavation and trenchless methods including directional boring, selecting the approach that best fits each Kenner project\'s conditions, budget, and timeline. Call (504) 301-2052 for a free assessment.' },
      ],
    },
  },
};
